### ISSUE TITLE
Skin disappear on server change

### ISSUE THREAD

**Issue by Feerko** [games647/ChangeSkin#103]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
When I set skin and go to other server my skin sets to previous. 
It's works normal when I set skin and quit from server and join. 

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Skin disappear:
/setskin name
/server hub
and i get previous skin

Skin works normal
/setskin name
quit from server
join to server
and i can change server and skin works

### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number , SQLite/MySQL, ...)
Bungeecord / mysql

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
3.0

### Configuration:

 
Config is default I just set mysql database

**Comment by Feerko** [comment]
I do not want to be naughty but can you fix it in the near future? This is a pretty serious bug.

**Comment by Feerko** [comment]
@games647 it's very important for me, please.

**Comment by games647** [comment]
You could also just downgrade to older versions
