### ISSUE TITLE
Sometimes skin doesn't work on join

### ISSUE THREAD

**Issue by Feerko** [games647/ChangeSkin#105]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
Sometimes when player join in server he losts their skin. On world change player's skin restores.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
I don't know, it's causes sometimes. I do not see dependence.

### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number , SQLite/MySQL, ...)
Bungee, MysSQL

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
3.0 (i compiled for my own from github)

### Error Log:
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error or stacktrace (if any)
there is no error

**Comment by games647** [comment]
And which commit did you compiled?

**Comment by Feerko** [comment]
https://github.com/games647/ChangeSkin/commit/c362131e0e293d5b4cb0818833c5f5c28dae4d3d

**Comment by games647** [comment]
Does the player loses the skin if the player joins directly or during a server switch?

**Comment by Feerko** [comment]
joins directly

**Comment by games647** [comment]
I think it could be a timing issue. Do you have server blacklist enabled?
