### ISSUE TITLE
Default skin

### ISSUE THREAD

**Issue by Ew9304** [games647/ChangeSkin#107]
Hello,

I amtrying to setup a default skin (d889f678-f960-4e35-b2fc-d7f72d9a34b6) so that new players who join the server do not have a skin set will become a Sloth. After updating the config in the Bungeecord plugins folder and the Spigot servers folder, New players who join the game still join as the default skins and not the one that I defined. I am running Spigot 1.8..8 and the latest Changeskins and Bungeecord using MySQL.

Aside from not being able to set a default skin, the plugin works great. but really need this feature.

Thanks

My config:

```
# Here you can specify default skins for player who do not have a skin
# The entries from this list will be selected in random order
#
# Lists are created like this:
#default-skins:
#    - 0aaa2c13-922a-411b-b655-9b8c08404695
#    - 069a79f4-44e9-4726-a5be-fca90e38aaf5
#
# If this list is empty no skin will be selected
default-skins:
- d889f678-f960-4e35-b2fc-d7f72d9a34b6
```

**Comment by Ew9304** [comment]
Does the player by any chance need to be a premium player for a default skin to apply or it should also work for cracked players? Sorry, I forgot to mention it at first.

**Comment by Ew9304** [comment]
Anything?

**Comment by games647** [comment]
Could you check again? It might be related to an error. If that was the case, next time please follow the issue template with the error log.

**Comment by Ew9304** [comment]
Hey, it still doesn't work. I tried the latest version and the dev build too. No errors on startup, Players join with default skins... 

default-skins:
    - 0aaa2c13-922a-411b-b655-9b8c08404695
    - 069a79f4-44e9-4726-a5be-fca90e38aaf5

**Comment by games647** [comment]
So you mean the default skins from Minecraft not ChangeSkin?

**Comment by Ew9304** [comment]
Yeah sorry I mean the default skins from Minecraft, I am really trying to get it so that players with no skin will join as a Sloth.. when the config is first created it is like 

`default-skins: []`

**Comment by games647** [comment]
Next time please post the complete config. It took some time until I discovered that this bug occurs if you have restoreSkins disabled.
