### ISSUE TITLE
New skins do not work

### ISSUE THREAD

**Issue by i0xHeX** [games647/ChangeSkin#110]
Since few days (as my players noticed) ago ChangeSkin stopped to download new skins.
Spigot 1.12.2 / ChangeSkin 2.4.2
No errors in console.

Steps:
- /skin i0xHeX (chat sends that all is okay and I need to rejoin)
- Rejoining
- No skin applied (however works with latest SkinsRestorer 13.3)

Tried:
- Remove local database and restart server

Configuration: https://hastebin.com/faxojujidi.vbs
It seems something changed on mojang api, as I know - rate limit became strongest.

**Comment by games647** [comment]
Please try with the latest build from the Jenkins instance.

**Comment by i0xHeX** [comment]
Nice, b52 works now.
