### ISSUE TITLE
FileNotFoundException for non premium users

### ISSUE THREAD

**Issue by i0xHeX** [games647/ChangeSkin#113]
Spigot 1.12.2 / ChangeSkin b54

On player join (non premium nickname):
https://hastebin.com/iwumejihax.swift
Try to set skin of premium player for non premium:
https://hastebin.com/uviniloguh.swift

**Comment by games647** [comment]
This is the first time I experienced this error on a getResponseCode() call. What Java version do you use (Oracle or OpenJDK) and could you test it with Java 8_161 or even Java 9?

**Comment by i0xHeX** [comment]
Java VM: Java HotSpot(TM) 64-Bit Server VM
Java Version: 1.8.0_152
Java Vendor: Oracle Corporation

**Comment by i0xHeX** [comment]
getResponseCode() returned something else not 204?
https://i.imgur.com/ET7FWUu.png

**Comment by games647** [comment]
No if you follow the stacktrace the exception occurred during the call instead of returning an integer representing the return code.

BTW: You could also checkout the source code directly. That might be easier to read. 

https://github.com/games647/ChangeSkin/blob/9ab5c44f734fbe467e03a25381f5cbbe18386513/core/src/main/java/com/github/games647/changeskin/core/MojangSkinApi.java#L90

**Comment by i0xHeX** [comment]
But exception occured on MojangSkinApi:107, then line getInputStream.
What you mean about local Mojang API proxy?

**Comment by i0xHeX** [comment]
I do not use any proxies and other webs, providing skins. Plugin runs like from the box, changed locale, default-skin: true and instant skin false.

**Comment by games647** [comment]
Do you still get this, because 404 (or 410?) would mean something is wrong at Mojang's API. It would only send a 204 for cracked users. I verified that some minutes ago.

**Comment by i0xHeX** [comment]
I added FileNotFoundException catch (with emulation as cracked user) and recompiled plugin yesterday. No problems for now idk.

**Comment by games647** [comment]
It's crazy, because you even got a FileNotFoundException for you (i0xHeX) and you [seem](https://api.mojang.com/users/profiles/minecraft/i0xHeX) to have a premium UUID.

**Comment by i0xHeX** [comment]
No no no, it reacts not on my nickname, but only if I join with non-premium nickname. I tried to set premium skin to cracked account.

**Comment by games647** [comment]
Yes but the plugin is independent on how login to the server. If it connects to the Mojang servers it should still be able to read your UUID.

**Comment by i0xHeX** [comment]
I think Mojang returned some other info not 204 when exception was.

**Comment by games647** [comment]
I know you added an additional catch, but if you still log them could you tell me if they are still happening?

**Comment by i0xHeX** [comment]
Okay, I will add logging on catch.

**Comment by games647** [comment]
If your server is hosted on a game server (not VPS or root), what hosting provider do you have?

**Comment by i0xHeX** [comment]
MelonCube

**Comment by games647** [comment]
Closing it for now, because I think it was a bug at Mojang's side and it's fixed now. I added now some additional logging in case it occurs again. Could you report back then? I'll reopen this if it's still happening.
