### ISSUE TITLE
Uploading skins dont work

### ISSUE THREAD

**Issue by kaktusyt** [games647/ChangeSkin#114]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?) 
Skin at mojang acc did not change after /skin-upload, and Skin-ID dont work.

### What behaviour is expected:
[//]: # (What did you expect?)
Just working skins.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail) 
/skin-upload [link], /skin-select [ID] 

### Plugin list:
[//]: # (This can be found by running `/pl`) 
ProtocolLib, ChangeSkin

### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number , SQLite/MySQL, ...) 
Spigot 1.12 R0.1

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)  
3.0

### Error Log:
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error or stacktrace (if any) 
-

### Configuration:
[//]: # (remember to delete any sensitive data) 
I think i dont need to show config, because in the console i saw successfully acc connect.
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file

**Comment by games647** [comment]
Please post the server log

**Comment by kaktusyt** [comment]
http://prntscr.com/i94u78 -> but skin has not changed
log: http://wklej.org/id/3360434/

**Comment by games647** [comment]
Please use a dev-build.

**Comment by kaktusyt** [comment]
I changed spigot and plugin to last dev build and now i have different error
http://wklej.org/id/3360443/ -> log

**Comment by games647** [comment]
403 means forbidden which could mean incorrect credentials.

**Comment by kaktusyt** [comment]
ok im generated new config and now acc is working but still skin is the same all time, and sometimes i see this error in the console:
http://wklej.org/id/3360445/

**Comment by games647** [comment]
429 means too many requests within one minute

**Comment by kaktusyt** [comment]
Now its working without errors but still skin is not uploading at mojang acc, after successful message

**Comment by games647** [comment]
It's uploading the skin, downloads it and changes it back.

**Comment by kaktusyt** [comment]
But why all ID's has the same signature, im uploading different skins

**Comment by games647** [comment]
Do you checked the database? The signatures should change on **every** requests

**Comment by kaktusyt** [comment]
http://prntscr.com/i958gw

**Comment by games647** [comment]
I cannot see there that the signature is the same. It just shows the datatype, here a blob (binary large object -> binary data)

**Comment by kaktusyt** [comment]
How can i check the signature?

**Comment by games647** [comment]
```SQL
SELECT HEX(signature) FROM skinData WHERE [...]
```
