### ISSUE TITLE
Bungeecord

### ISSUE THREAD

**Issue by xan61789** [games647/ChangeSkin#117]
Hi, ChangeSkin will not work on my server
I use a Spigot server , I have checked 
ip_forward: true
bungeecord: true
bukkit-permissions: true
But he still did not respond , Please help me, thank you

**Comment by games647** [comment]
Do you followed the BungeeCord setup guide (included enabled MySQL/MariaDB)?

**Comment by xan61789** [comment]
But my server did not use MySQL , Is he necessary?

**Comment by games647** [comment]
https://github.com/games647/ChangeSkin#how-to-install-on-bungeecord

>For example BungeeCord doesn't support SQLite by default

Yes because BungeeCord doesn't include a driver for SQLite like Spigot/Bukkit/Paper does.

**Comment by xan61789** [comment]
Okay, is that easy to teach? 
I do not want to synchronize all the information, just want to sync ChangeSkin this plugin

**Comment by games647** [comment]
Configuring MySQL/MariaDB isn't that hard and it's necessary to store the skins.

**Comment by xan61789** [comment]
Do not understand .... Sorry

**Comment by xan61789** [comment]
![2018-02-08_014710](https://user-images.githubusercontent.com/33800409/35932202-0dec958a-0c72-11e8-826b-54eca954f34e.png)

Fill in the information here? What to fill in?

**Comment by games647** [comment]
The table will be created automatically. You just need to create a database or use an existing one.

**Comment by xan61789** [comment]
Sounds very handy, so should I go back to the previous step?

**Comment by games647** [comment]
You still need to put the relevant details about your MySQL into the config.
