### ISSUE TITLE
How do I change another player's skin?

### ISSUE THREAD

**Issue by ziceptor** [games647/ChangeSkin#118]
By its uuid. Using skin-select (from DB). It is necessary for the npc (VillagerShop). Is that possible?

**Comment by games647** [comment]
Yes it's would be possible with ChangeSkin, but for Citizens the API is broken.

https://github.com/CitizensDev/CitizensAPI/issues/30

**Comment by ziceptor** [comment]
I'll clarify a little bit. How to change the uuid of another player skin. Sponge. CitizensAPI not for sponge. 

Perhaps it is crossed with https://github.com/games647/ChangeSkin/issues/102

**Comment by games647** [comment]
So you want to modify the skin of the player with UUID ___? (Where ___ means the command argument)

**Comment by ziceptor** [comment]
Something like that  (from DB): /skin-select <UUID> <SkinID>

**Comment by ziceptor** [comment]
UUID from player

**Comment by ziceptor** [comment]
Any news?

/skin-select <Player UUID> <SkinID>

Will this work for EntityTypes.PLAYER?

**Comment by games647** [comment]
No currently not. I'm currently working on refactoring major parts of the plugin to make it more maintainable. Next I'm planning to include a new command library (aikar's commands) for easier and more flexible command parsing.

>Will this work for EntityTypes.PLAYER?

No this won't work atm.

**Comment by games647** [comment]
@ziceptor  Why do you closed it?

**Comment by ziceptor** [comment]
Label "question". I think it's crossed with https://github.com/games647/ChangeSkin/issues/102
 If I'm wrong, you can open it. Sorry for bad English.
