### ISSUE TITLE
Crash when using changeskin in 1.12.2

### ISSUE THREAD

**Issue by sergio2887** [games647/ChangeSkin#121]
### What behaviour is observed:
I installed the plugin and the server has sent me, before in 1.10.2 I did not pass, but since I am in 1.12.2 if I crashed

### What behaviour is expected:
I was hoping you would give me a possible solution to the crash

### Steps/models to reproduce:
I do not know exactly why the problem occurs, install the ChangeSkin plugin from spigot (since according to you it is universal) and I added protocolLib

### Plugin list:
In the unique version of sponge if the plugin comes out, but the commands do not appear

### Environment description
It is an independent server, without bungeecord

### Plugin version or build number (don't write latest or the build number with #):
ChangeSkin 3.1

### Error Log:
https://gist.github.com/sergio2887/9f8000d7614d5dec814e11426e13cba0

### Configuration:
https://gist.github.com/sergio2887/4e6443fe7e75b5fdba74d1103090ef84

**Comment by games647** [comment]
Which build number do you use?

**Comment by sergio2887** [comment]
spongeforge-1.12.2-2611-7.1.0-BETA-2931

**Comment by games647** [comment]
Sorry I meant of ChangeSkin.

**Comment by sergio2887** [comment]
I think the version 3.1 The universal that is downloaded from spigot

**Comment by games647** [comment]
Please try it with a dev build, I think I already fixed it.

**Comment by sergio2887** [comment]
I put the version that you passed me, but in the minecraft I do not get commands I put:
/ setskin and I get unknown command.

Install the ChangeSkinSponge version only, do you need anything else?
and ... can you send me the download link of both the add-on and the necessary one?

I have installed https://ci.codemc.org/view/Games647/job/ChangeSkin/68/ this version

**Comment by games647** [comment]
Please post the sponge server log. Yes you only need ChangeSkinSponge.

**Comment by sergio2887** [comment]
![image](https://user-images.githubusercontent.com/36729553/36600755-7001bd66-18b3-11e8-8de4-afe7d686dbb2.png)

Which of these?

**Comment by games647** [comment]
Yes

**Comment by sergio2887** [comment]
lastest.log?

**Comment by games647** [comment]
Yes the latest log.

**Comment by sergio2887** [comment]
[latest.log](https://github.com/games647/ChangeSkin/files/1752143/latest.log)

**Comment by games647** [comment]
Could you try # 67?

**Comment by sergio2887** [comment]
yes, i use #67... i see that you upload the #69

**Comment by games647** [comment]
It's from the continuous integration that builds the project automatically when I upload changes.

**Comment by sergio2887** [comment]
Will it be solved?

**Comment by games647** [comment]
Do you tried # 69?

**Comment by sergio2887** [comment]
no

**Comment by games647** [comment]
Then please do
https://github.com/games647/ChangeSkin/issues/121#issuecomment-368052294

**Comment by sergio2887** [comment]
java.lang.NullPointerException: null
	at com.github.games647.changeskin.core.shared.SharedDownloader.run(SharedDownloader.java:25) ~[SharedDownloader.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2611-7.1.0-BETA-2931]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-2931]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by sergio2887** [comment]
error to ejecute command

**Comment by games647** [comment]
Please post the complete log.

**Comment by sergio2887** [comment]
in lastets.log not appear.

**Comment by sergio2887** [comment]
[fml-junk-earlystartup.log](https://github.com/games647/ChangeSkin/files/1752503/fml-junk-earlystartup.log)

**Comment by games647** [comment]
This is the source error
>[18:00:55] [Server thread/ERROR] [changeskin]: This driver  is not supported on this platform

Could you please post your server configuration?

**Comment by sergio2887** [comment]
server-properties?

**Comment by games647** [comment]
Please read again. I edited it. Plugin configuration file.

**Comment by sergio2887** [comment]
Config.YML: https://gist.github.com/sergio2887/e4a5188f04b4a6c773ae5c5a08aa2365

ChangeSkin.conf: https://gist.github.com/sergio2887/b241b4162e8f370080e8e03e2e8b3577

**Comment by games647** [comment]
Where do people even get those configuration files? This isn't the ChangeSkin configuration (The content is completely different). Please delete it. This is how the configuration should look like:

https://github.com/games647/ChangeSkin/blob/master/core/src/main/resources/config.yml
