### ISSUE TITLE
Skin changing in Sponge

### ISSUE THREAD

**Issue by Vizis** [games647/ChangeSkin#122]
Have you removed /skinupload command? 
Cause i wounder if there is any option to upload skin, and then upload cape for it. Maybe diffrent command?
Also is there any other option to change skin from file? I see in db the  SkinURL value it's kind of hash... Do im ablue to upload skin fron file via php script?

**Comment by games647** [comment]
No I didn't removed the upload command. Currently I only found a way to upload the skin, but not the cape. I don't think will ever be changeable from Mojang servers. 

>Also is there any other option to change skin from file?

No that isn't possible sorry. Mojang forces that skin should be signed by Mojang. This means that the skin have to uploaded once to their servers. Then we could download the skin from there with a valid signature. After that you could change your skin back while still having a reference to the uploaded skin.

>Do im ablue to upload skin fron file via php script?

Yes you could also upload skins with PHP. This here is great resource on how to upload skins using the Mojang API: http://wiki.vg/Mojang_API#Upload_Skin

**Comment by Vizis** [comment]
Than you

**Comment by Vizis** [comment]
Also, all users have to have CS in thier mods to see other players skins?
Cuse i have change my skin and my friend didnt seen that.

**Comment by games647** [comment]
>Also, all users have to have CS in thier mods to see other players skins?

No ChangeSkin is only server-side. 

>Cuse i have change my skin and my friend didnt seen that.

I guess you are using Sponge? Skins from other players are only possible if the player settings are reloaded. ChangeSkin does that by making the player hidden and show it again. I assume it doesn't work in Sponge.

**Comment by Vizis** [comment]
Hm strange thing. I have to restart  server because when i was before on server /skin command woked fine, scren was blinking <like reloadking resource pack> then my skin was changed. Now after dissconect and reconnect to server /skin comand just shows info about dling and changing uuid of skin but changes nothing and not blinking my screen. and yes, i;m on sponge.

**Comment by games647** [comment]
Could you post your server log please?

**Comment by Vizis** [comment]
[fml-junk-earlystartup.log](https://github.com/games647/ChangeSkin/files/1778539/fml-junk-earlystartup.log)
also /setskin reset gives nice error in logs. bw im on MySql

**Comment by Vizis** [comment]
What does KeepSkin in preferences db?

**Comment by games647** [comment]
You used an invalid command syntax. You should use /skin playerName or /skin uuid just in the ReadMe. 

>also /setskin reset gives nice error in logs. bw im on MySql

Do you modified something on the database manually?

>What does KeepSkin in preferences db?

Should the skin be auto updated or kept using the database cache.

**Comment by Vizis** [comment]
Yep as i said i have deleted skinData and taht was the problem, I fixed AI in records and every works fine now
