### ISSUE TITLE
Sponge - Permissions doesn't work

### ISSUE THREAD

**Issue by Vizis** [games647/ChangeSkin#123]
SpongeForge 1.12.2-2611-7.1.0-BETA-2931.jar
ChangeSkinSponge.jar "3.1-61cc473"
+ Lucky Perms

Group remission changeskin.command.setskin.* set to 0 (false)
but skill i can use /setskin ( i set long cd so i get message from coldown module)

[i've set also my nucleus.fly.base to 0 and it works like it should" you have no permission bla bla"]

And also can you ad in future builds expiry time or time of use in database?
For reset cd for user on demnad

Also2, i think it would be great idea to add permision to setskin.name or sth like this to let players use only command with his nick ( for premium users who play on server with offlinemode to let him use his own skn)

**Comment by games647** [comment]
>And also can you ad in future builds expiry time or time of use in database?

You mean automatically reset the skin after the time expires? Please put that into a seperate ticket. It's better to categorize the tickets.

>Group remission changeskin.command.setskin.* set to 0 (false)

That permission is only used for whitelisting certain permission. That you possible mean is changeskin.command.setskin

I think Sponge commands doesn't have any permissions currently. I'll fix it now.

**Comment by Vizis** [comment]
#NoHomo but i love you 
I'll write separate ticket and describe it clearly

**Comment by games647** [comment]
>Group remission changeskin.command.setskin.* set to 0 (false)

Looks like Sponge has a [different permission inheritance model](https://docs.spongepowered.org/stable/en/plugin/permissions.html). Where `changeskin.command.setskin` means all permissions including [...].setskin.other. I hope that is okay for you.

**Comment by Vizis** [comment]
It's a bit bad to let user to change other players skins but it it;s impassible to do it has to be ok... better than no permissions at all

**Comment by Vizis** [comment]
I think it's still possible. Maybe it's jsut a bit of a work cause when i read a nucleus documentation i see for exmaple tp command have permissions 
nucleus.teleport.teleport.base
 and to let tp others 
nucleus.teleport.teleport.others
or just to use all functions 
nucleus.teleport.teleport.*

**Comment by games647** [comment]
Currently changing other skins isn't even implemented in Sponge. It just was never were requested before. 

>I think it's still possible. Maybe it's just a bit of a work cause when i read a nucleus documentation i see for exmaple tp command have permissions

That would be an idea, but breaks existing permissions for BungeeCord and Bukkit. I'll fix it for Sponge and add a note that the Bukkit and BungeeCord module will be migrated to the same logic in the next major version.
