### ISSUE TITLE
Question: default-skin

### ISSUE THREAD

**Issue by Vizis** [games647/ChangeSkin#125]
How i should setup this to everybody gets default skin i set?
this is corret uuid: 45cdd7ef84ed401bbc2d60537698ec89
when i jsut set there "default-skins: [45cdd7ef84ed401bbc2d60537698ec89]" it was wrong and plugin was disabled on startup.
~ < comment sign cause hash is bad here
~default-skins:
~    - 0aaa2c13-922a-411b-b655-9b8c08404695
~    - 069a79f4-44e9-4726-a5be-fca90e38aaf5
~
~ If this list is empty no skin will be selected
default-skins: []

**Comment by games647** [comment]
Default skins should have this format
https://github.com/games647/ChangeSkin/blob/48c2cc4d52354e0158915a6e6b12d799dd9baea2/core/src/main/resources/config.yml#L6-L12

To give a more concrete example:

```yaml
default-skins:
    - 0aaa2c13-922a-411b-b655-9b8c08404695 
    - 069a79f4-44e9-4726-a5be-fca90e38aaf5 
```

**Comment by ziceptor** [comment]
Is it possible to make such a setting, be used skins from the database?

default-skins:
    - 12

**Comment by DoNotSpamPls** [comment]
@ziceptor If you really want it, it'd be better to post it as a new issue, not as a comment to an existing one.

**Comment by ziceptor** [comment]
Will leave it to the discretion and desire of the developer.
