### ISSUE TITLE
Multiple BungeeCord support

### ISSUE THREAD

**Issue by tuanjr** [games647/ChangeSkin#13]
- install on bungeecord and every server on network, connect all to one database?
- or install only on bungeecord?
- or install on bungeecord and every server on network, but only config in bungeecord has connect to database?

**Comment by games647** [comment]
Only on Bungee

**Comment by tuanjr** [comment]
if i have multiple bungeecord (redis bungee), so connect in to one database work?
i mean does this plugin support redisbungee?

**Comment by games647** [comment]
I guess no, because it caches it locally.

**Comment by tuanjr** [comment]
i mean "one MySQL database", not SQLi. i gues it work?

**Comment by games647** [comment]
Yes, but ChangeSkin caches it in memory.

**Comment by games647** [comment]
Update to support multiple BungeeCord will coming soon. I'm currently working on massive refactoring to support it. It's be released after intense testing. So you can expect it within the next three days. 

Sorry for the big delay. I was too busy.

**Comment by tuanjr** [comment]
Thank, i cant wait for this! :)
