### ISSUE TITLE
Changeskin doesn't work with SpongeForge and Bungeecord

### ISSUE THREAD

**Issue by BadassOverlord** [games647/ChangeSkin#130]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
Cannot join minecraft server, PlayerDisconnected message appears.

### What behaviour is expected:
[//]: # (What did you expect?)
Log in to the minecraft server

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Install SpongePls and ChangeSkin on Bungeecord, and use MySQL as the server
Install ChangeSkin on SpongeForge and setup sponge for bungeecord ip forwarding
Both BungeeCord and the Sponge server are in offline mode.
Attempt to connect to the spongeforge server via bungeecord.
### Plugin list:
[//]: # (This can be found by running `/pl`)
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BungeeTabListPlus-SpongeBridge, ChangeSkin, FlexibleLogin, GriefPrevention, KaroglanSignEditor, LuckPerms, MMCRestrict, Market, Nucleus, PlaceholderAPI, PlayerShopsRPG, ProjectCore, ProjectWorlds, Total Economy, UltimateChat, WorldEdit

### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number , SQLite/MySQL, ...)
MySQL
Bungeecord build #1305

### Plugin version or build number (don't write latest or the build number with #):
[//]: # (This can be found by running `/version plugin-name`.)
3.1

### Error Log:
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error or stacktrace (if any)
https://pastebin.com/PrStSdcZ

### Configuration:
[//]: # (Remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://pastebin.com/LAPRFfet

**Comment by BadassOverlord** [comment]
I forgot to mention - removing the ChangeSkin plugin from the bungeecord plugins directory completely fixes the problem, so I think it's probably something to do with ChangeSkin

**Comment by games647** [comment]
What message does the client see? 

And please post the complete version next time. The commit id is missing.

**Comment by games647** [comment]
What version of SpongeForge do you use?

**Comment by BadassOverlord** [comment]
spongeforge-1.12.2-2611-7.1.0-BETA-2977
changeskin.sponge-3.1 #100 (23-Mar-2018 12:07:54)
bungeecord #1​30​5 15-Mar-2018 09:47

I hope that's the complete version.

**Comment by BadassOverlord** [comment]
Oh and here's the message that the client sees:
![image](https://user-images.githubusercontent.com/12927314/37868066-3540a964-2f5e-11e8-8527-2d681d631124.png)

And finally, here's the full log of bungeecord (nothing appears on the actual server, because the player never gets that far): https://pastebin.com/sZ8yB8cX

I removed the IP addresses from the bungeecord log.

**Comment by games647** [comment]
BTW don't write #Number It's used to link to other tickets.

This disconnected shows up if there is something wrong during login process. Could you check the forge server log for any errors?

It could be a combination of SpongePls with mods and ChangeSkin.

**Comment by BadassOverlord** [comment]
Also, the same thing happens even if I disabled SpongePls, so I doubt it's SpongePls.

**Comment by games647** [comment]
Do you also enabled bungeecord support inside the Sponge global config (not only ip forwarding)?

**Comment by BadassOverlord** [comment]
Yes I have

`bungeecord {
        # If 'true', allows BungeeCord to forward IP address, UUID, and Game Profile to this server.
        ip-forwarding=true
    }`

**Comment by games647** [comment]
And this?

```HOCON
    modules {
        [...]
        bungeecord=true
        [...]
    }
```
