### ISSUE TITLE
Problem with auto-skin-update

### ISSUE THREAD

**Issue by Reeferx7** [games647/ChangeSkin#132]
The option auto-skin-update: 1 dont work at all the new skins never auto update.

### Environment description
I test it in all this:
Standalone server, bungeecord, SQLite and MySQL

ver: CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)

### Plugin version or build number (don't write latest or the build number with #):
ChangeSkin version 3.1-3882ba3

### Error Log:
Non

### Configuration:

https://pastebin.com/AdhZQALF

**Comment by games647** [comment]
Please follow the issue template. How did you tested it?

**Comment by Reeferx7** [comment]
Hello @games647 just i set my config like this i join to the server, then i leave, i change my skin and after 5 minutes i rejoin and skin dont change, i try a lot times after more time. i test with SQLite and mysql 
bungeecord and spigot single server.

**Comment by games647** [comment]
>i join in other servers too and i have my new skin,

So it does work after you join other servers?

**Comment by Reeferx7** [comment]
Premium servers yes!

**Comment by games647** [comment]
Could you try a newer dev-build please?

**Comment by Reeferx7** [comment]
@games647 Now work fine, thanks a lot.
