### ISSUE TITLE
Not working error on spigot 1.12.2-R0.1-SNAPSHOT

### ISSUE THREAD

**Issue by Sitieno14** [games647/ChangeSkin#135]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

### What behaviour is observed:
[//]: # Error in console and command is not working

### What behaviour is expected:
[//]: # Executed command (/skin set)

### Steps/models to reproduce:
[//]: # /skin set

### Environment description
[//]: # Standalone server

### Plugin version or build number:
[//]: # 3.0

### Error Log:
https://gist.github.com/Sitieno14/2a5bc5e00d95497b73a3d3580589e793

### Configuration:
[//]: # Default configuration

**Comment by games647** [comment]
Please report it to PerWorldPlugins. This seems like a bug in their code.

>        at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]

**Comment by Sitieno14** [comment]
Solved, I'm sorry, it was the config c.c
