### ISSUE TITLE
ClassNotFound com.google.gson.Gson

### ISSUE THREAD

**Issue by xGlenor** [games647/ChangeSkin#141]
I have Problem
Help me

http://prntscr.com/jr7mta

**Comment by games647** [comment]
Please follow the issue template. Do you use an unmodified version of Spigot 1.8.8? 

BTW: Never post screenshots of errors. It's always post the textual representation.

**Comment by xGlenor** [comment]
i have Spigot 1.8

**Comment by games647** [comment]
Sorry, but this plugin only supports 1.8.8, because this library is required.
