### ISSUE TITLE
Client doesn't see any chunks on instant update

### ISSUE THREAD

**Issue by mat41997** [games647/ChangeSkin#15]
/skin off
/skin off
/skin off
![2016-06-09_20 49 42](https://cloud.githubusercontent.com/assets/5884000/15942536/1b54dcd6-2e85-11e6-92ea-befac114e395.png)

F3+A
![2016-06-09_20 57 40](https://cloud.githubusercontent.com/assets/5884000/15942552/2407b646-2e85-11e6-89d6-5024f5b88f2d.png)

Timings
(deleted)

New Timings
https://timings.aikar.co/v2/?id=b13bebeba765474b90ea23926b608cf2

**Comment by games647** [comment]
I cannot reproduce it. Could I see a plugin list?

**Comment by mat41997** [comment]
see timings : O

overlap "Plugin List"

**Comment by games647** [comment]
Do you deleted the timings report?

**Comment by tuanjr** [comment]
i have same problem, when player run /skin command on "pvp time" (combat time, pvpmanager plugin).

**Comment by games647** [comment]
@tuanjr With BungeeCord?

**Comment by tuanjr** [comment]
@games647 yes.

**Comment by games647** [comment]
@tuanjr  Do you have ProtocolLib installed?

**Comment by tuanjr** [comment]
protocollin install on bukkit? yes, i have

**Comment by tuanjr** [comment]
Current, on my network, ChangeSkin install only on bungeecord, as you said in another topic. But with this way, player must logout to update skin. If install ChangeSkin on BungeeCord, connect to Mysql, and install ChangeSkin on every bukkit server, with this way, skin update instant.
So what is correct way to install?

**Comment by games647** [comment]
Yes Indeed and activate bungeecord support in your spigot config. Sorry for that.

**Comment by games647** [comment]
@tuanjr Do you see the new skin or do you have the same chunk issues like @mat41997

**Comment by tuanjr** [comment]
i have the same chunk issues like mat41997. As i said 

> i have same problem, when player run /skin command on "pvp time" (combat time with pvpmanager plugin).

**Comment by games647** [comment]
I think a plugin is blocking my teleport request.

**Comment by games647** [comment]
Could you try that:
https://github.com/games647/ChangeSkin/releases/tag/1.4.1

**Comment by mat41997** [comment]
is beter
![2016-06-10_12 57 14](https://cloud.githubusercontent.com/assets/5884000/15962390/0b345602-2f0b-11e6-8169-5c24ec83f7c7.png)

**Comment by games647** [comment]
:D

**Comment by games647** [comment]
New version is uploaded. Same link. It will now check if the teleport was succesfull. If not, send the chunks manually in a 3*3 radius.

**Comment by mat41997** [comment]
still not works : O

**Comment by games647** [comment]
You used the version from spigot?

**Comment by games647** [comment]
@mat41997 Could you try? https://github.com/games647/ChangeSkin/releases/tag/1.4.1
