### ISSUE TITLE
Bungee > Spigot  Mysql

### ISSUE THREAD

**Issue by Blackyvk** [games647/ChangeSkin#152]
For this plugins to work 100%, If i have 1 bungee and 2 spigot, I need to connect all 3 to mysql?  right? 
There is no way for bungee to handle all? so Spigot just send/receive the information and handle only commands, just to avoid mysql connections.

Same question for FastLogin...

**Comment by games647** [comment]
Same as FastLogin, in BungeeCord environments they act as master and slave instances. The BungeeCord module will connect to the database and issue commands while the Bukkit module will act on Bukkit specific input and perform the issued commands.

**Comment by Blackyvk** [comment]
so, in few words, I dont need to setup database on spigot side, just leave it blank or what?

**Comment by games647** [comment]
Yes
