### ISSUE TITLE
ChangeSkin make the spongeforge server crash [v1.12.2]

### ISSUE THREAD

**Issue by LorenzoMontanoPecoraro** [games647/ChangeSkin#163]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

What behaviour is observed:
When I start the server, during the ChangeSkin load, it crashes

What behaviour is expected:
To start the server

 Steps/models to reproduce:
1 Make a SpongeForge server
2 Place ChangeSkin and ProtocolLib in the mods folder
3 Start the server and enjoy the crash!
Plugin list:
Just ChangeSkin and ProtocolLib

Environment description:
Spongeforge 1.12.2-2825-7.1.6
Windows 10

Plugin version or build number:
3.0

Error Log:
https://gist.github.com/LorenzoMontanoPecoraro/f68e0b1b8a8d2db977c8cdbff89b74e8

 Configuration:
There isn't any

**Comment by games647** [comment]
Please download a development build. It should be already fixed.

**Comment by LorenzoMontanoPecoraro** [comment]
OK THX. Know it works
