### ISSUE TITLE
Sponge support

### ISSUE THREAD

**Issue by GershonR** [games647/ChangeSkin#18]
I would use this if it worked for Sponge

**Comment by games647** [comment]
As far as I know the skin API in Sponge isn't implemented yet.

**Comment by GershonR** [comment]
Do you know if it's being worked on, almost done or not even added yet, I get requested skins a lot by players

**Comment by games647** [comment]
Okay I was wrong. It does work.

**Comment by GershonR** [comment]
Sponge has the skin API?

**Comment by games647** [comment]
Yes

**Comment by GershonR** [comment]
Will this plugin be made for it then?

**Comment by games647** [comment]
Yes. I'm working on it.

**Comment by GershonR** [comment]
Ok awesome thanks alot!

**Comment by games647** [comment]
I'm planning to add Sponge support today. Instant update support for changing skins while playing will be added later. I first want to test if everything works.

**Comment by games647** [comment]
Refetching the skin already works.

**Comment by GershonR** [comment]
Awesome look forward to testing this!

**Comment by games647** [comment]
Download: https://github.com/games647/ChangeSkin/releases/tag/1-7-sponge

**Comment by GershonR** [comment]
http://pastebin.com/gaTJNdDJ

Error when trying to change a skin, and it didn't change on login but not sure if it was suppose to

**Comment by games647** [comment]
You are not using the right sponge version. It's compiled against Sponge 5

**Comment by GershonR** [comment]
Is it possible to downgrade to 1.8.9 since it's still not recommended or just support it and most plugin are 1.8.9, also when I world hopped it seemed to have applied the skin and the config and everything seems to be working

**Comment by games647** [comment]
You could also disable the instant updates since it's only possible in sponge to make the new skin visible to others while being in game.

**Comment by GershonR** [comment]
Ok now after relogging it seems to show your skin to everyone so I think just asking the user to relog but be the easiest way

**Comment by games647** [comment]
That's what happens on disabled instant updates

**Comment by GershonR** [comment]
if I use the restoreSkins: feature, they will have to relog correct?

**Comment by games647** [comment]
RestoreSkins means it will download the skins of cracked players.

What you mean is instant updates.

**Comment by GershonR** [comment]
Like when they login will they be steve/alex and they will have to relog to see their skin?

**Comment by games647** [comment]
On login skins can be applied instantly. The option instant-updates is for ingame, which you have to disable. 

RestoreSkins means it will download the skin from mojang based on the username. If you disable it players, have to do it by hand.

**Comment by GershonR** [comment]
Yep I just tested restoreskins works perfectly, everything seems to be working good a command to reload the config would be really cool like
/changeskin reload incase you want to change the cooldown or the options

Also changeskin [player] [skin] would be nice for admins in-case someone uses a hitler skin or something...

**Comment by GershonR** [comment]
Not sure if I did it right but I tried out the default skins feature by uncommenting from the config but i'm not sure if I did it right:
default-skins:

    - 93e4e551-589a-41cb-ab2d-435266c8e035

    - e6484765-f4e9-4116-8a56-e4f3899e616d

    - 764a000d-171f-4b6e-b567-2e7673947139

Diden't work I also tried:

default-skins: [93e4e551-589a-41cb-ab2d-435266c8e035]

**Comment by games647** [comment]
They are only set if the has no skin. This means no skin from the restore skins feature and no custom skin.

**Comment by GershonR** [comment]
ooohhhh I get it, is it possible to make it use default if they have a steve or alex skin?

**Comment by games647** [comment]
Sorry that's impossible.

**Comment by GershonR** [comment]
Ok I see thanks, I thought it was meant to replace the default steve/alex skins
