### ISSUE TITLE
Skin dont save on reconnect

### ISSUE THREAD

**Issue by Nextopi** [games647/ChangeSkin#186]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

### What behaviour is observed:
Skins dont stay on reconnect

### What behaviour is expected:
Keep the skin

### Steps/models to reproduce:

1/setskin name
2 disconnect from server
3 reconnect

Skin works again if you use /skinupdate but are lose all the time with reconnect, (old skins that were used long ago work)

### Plugin list:
Luckperms, litebans, networkmsgs, fastlogin, changeskin, nuvotifier

### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number, SQLite/MySQL, ...)
Tested on bungee and paper aswell
waterfall-341
git-Paper-214 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Plugin version:
[//]: # (Don't write latest or the build number with #. #Number is used to reference to other tickets.)
[//]: # (This can be found by running `/version plugin-name`.)
 ChangeSkin version 3.1-SNAPSHOT-a9b5cb0
### Error Log:
None

### Configuration:
[//]: # (Remember to delete any sensitive data)
https://hastebin.com/oxotuporor.makefile

**Comment by H4kt** [comment]
Having trouble with it too
Running latest paper 1.12.2 & BungeeCord BotFilter (which uses the latest BungeeCord build)

**Comment by games647** [comment]
Super seeded by #187
