### ISSUE TITLE
error - AsyncPlayerPreLoginEvent

### ISSUE THREAD

**Issue by mat41997** [games647/ChangeSkin#2]
logs
http://hastebin.com/nakotonozu.avrasm

i use Authme Reloaded dev #948
http://ci.xephi.fr/job/AuthMeReloaded/948/

and other plugins..

**Comment by games647** [comment]
Which user is that, because it looks like it's a premium username without a skin.

**Comment by mat41997** [comment]
i dont have idea
http://hastebin.com/iyorebucul.tex

**Comment by games647** [comment]
Thanks that's all I need to fix it.

**Comment by games647** [comment]
Thank you for reporting it. It's fixed for 0.9
