### ISSUE TITLE
instantSkinChange not work on bungeecord?

### ISSUE THREAD

**Issue by tuanjr** [games647/ChangeSkin#21]
instantSkinChange not work when run on bungeecord? player must re log to update skin.

**Comment by games647** [comment]
It works for me. Do you still have ChangeSkin on the backend server.

**Comment by tuanjr** [comment]
you mean Changeskin on spigot? No, only ChangeSkin on Bungeecord.

**Comment by games647** [comment]
For that feature it's required to be on the Spigot server too, because this requires packet manipulation which BungeeCord doesn't support.

**Comment by tuanjr** [comment]
oh, so ChangeSkin must install every spigot server? why another topic, i ask you how to install changeskin in bungeecord, you said "only bungeecord" :D
you need write install tutorial :D

**Comment by games647** [comment]
>why another topic, i ask you how to install changeskin in bungeecord, you said "only bungeecord" :D

It's already on the project page ^^

I thought you already have it installed in this way based on https://github.com/games647/ChangeSkin/issues/15#issuecomment-225136195
