### ISSUE TITLE
SQL bad insertion

### ISSUE THREAD

**Issue by FixedDev** [games647/ChangeSkin#217]
https://github.com/games647/ChangeSkin/blob/9da68d329569a5bde18b27a346371906a68d43c3/core/src/main/java/com/github/games647/changeskin/core/SkinStorage.java#L195

As known by lots of previous issues, there's a data race when multiple saves are being done. This could be fixed by using `INSERT... ON DUPLICATE KEY UPDATE` on MySQL and `INSERT OR REPLACE INTO` in SQLite.

The downside of this is that MySQL and SQLite queries would be different, but that would solve the problem.

**Comment by games647** [comment]
Thanks for bringing this up, but the plugin acquires a lock on the data model. Outside of multiple BungeeCords this would be then safe to do.

**Comment by games647** [comment]
I guess you used an outdated version where this wasn't case.

**Comment by games647** [comment]
Closing due inactivity. The only point that it would still matter would be multiple BungeeCords. However I think using `Replace INTO` is more like a workaround instead of solution to that.
