### ISSUE TITLE
issues with tablist and custom heart!

### ISSUE THREAD

**Issue by tuanjr** [games647/ChangeSkin#22]
After success change skin, player lose their rank, like in image:
![](https://www.dropbox.com/s/bfo8s60dhq2olx7/x.png?raw=1)
and lose custom heart
![](https://www.dropbox.com/s/0huqj0ihf37knjd/d.png?raw=1)
changeskin install on bungeecord and every spigot
tablist use titlemanager plugin
protocolib 4.0.1 version

**Comment by games647** [comment]
How do you set the custom hearts?

**Comment by tuanjr** [comment]
i use this plugin: https://www.spigotmc.org/resources/permissionshealthrecoded.16175/

**Comment by tuanjr** [comment]
This is issues still not fixed in version 1.8
and, config file not automatic update.

**Comment by games647** [comment]
>and, config file not automatic update.

That's normal

**Comment by tuanjr** [comment]
@games647 
issues with heart is fixed, but issues with tablist is not fixed. 
I use ChangeSkin 1.11

**Comment by games647** [comment]
What plugins do you have?

**Comment by tuanjr** [comment]
i use title manager https://www.spigotmc.org/resources/titlemanager.1049/

**Comment by games647** [comment]
I'm sorry, but titlemanager has to hook into ChangeSkin as it does for VanishNoPacket, superVanish,...
