### ISSUE TITLE
Auto-Skin-Update with blacklisted servers

### ISSUE THREAD

**Issue by andris155** [games647/ChangeSkin#220]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
The skins no updated when enabled the auto-skin-update setting.

### What behaviour is expected:
[//]: # (What did you expect?)
The skins updated when enabled the auto-skin-update setting.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
1. Set auto-skin-update to 20 minutes.
2. Join to the server and left.
3. Change skin.
4. Wait 20 minutes.
5. Join again the server.
6. The skin not updated.

### Plugin list:
[//]: # (This can be found by running `/pl`)
<img width="125" alt="Screenshot 2021-05-16 134019" src="https://user-images.githubusercontent.com/8324198/118395740-449f6a80-b64c-11eb-96c3-6b6c43b600ba.png">

### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number, SQLite/MySQL, ...)
Waterfall 1.16-R0.5-SNAPSHOT build 416, SQLite.

### Plugin version:
[//]: # (Don't write latest or the build number with #. #Number is used to reference to other tickets.)
[//]: # (This can be found by running `/version plugin-name`.)
3.1-SNAPSHOT-9da68d3

### Configuration:
[//]: # (Remember to delete any sensitive data)
https://pastebin.com/6rfpy0GL

**Comment by games647** [comment]
What's the output of `/skin-info` including the unix timestamp at the time you joined the server (doesn't have to be that precise - minute is enough)?

https://www.unixtimestamp.com/

**Comment by andris155** [comment]
Skin updated/fetched: 1621164533646
Joined: 1621192517

**Comment by games647** [comment]
Does the skin has the keepSkin property set?

**Comment by andris155** [comment]
I don't think so, but I don't know where to see this.

**Comment by andris155** [comment]
Thanks!
