### ISSUE TITLE
Plugin not working on Paper 1.16 #775 + ProtocolLib 4.6.0

### ISSUE THREAD

**Issue by rafaelsms** [games647/ChangeSkin#223]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
With the default configuration on a test server, I'm getting
`com.comphenix.protocol.reflect.FieldAccessException: No field with type int exists in class PacketPlayOutRespawn`
when using the command.
After disabling `instantSkinChange`, there is no error but the skin isn't applied upon rejoining.

### What behaviour is expected:
[//]: # (What did you expect?)
Skin change without errors and when rejoining.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)

### Plugin list:
[//]: # (This can be found by running `/pl`)
`Plugins (6): AuthMe, ChangeSkin*, Essentials, ProtocolLib, Themis, ViaVersion`

### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number, SQLite/MySQL, ...)
Default configuration with a standalone Paper server #775 (1.16.5)

### Plugin version:
[//]: # (Don't write latest or the build number with #. #Number is used to reference to other tickets.)
[//]: # (This can be found by running `/version plugin-name`.)
Latest on SpigotMC website and latest on CI.

### Error Log:
[exception stack trace](https://hastebin.com/sodakovuvo.yaml)

### Configuration:
[//]: # (Remember to delete any sensitive data)
[configuration](https://hastebin.com/bihikejame.yaml)

**Comment by games647** [comment]
V3.0 is very outdated. Please provide the logs from the CI version.

**Comment by rafaelsms** [comment]
Yeah, must be it :) Tried on my local server and couldn't reproduce. Thank you!
