### ISSUE TITLE
ChangeSkin error on 1.17

### ISSUE THREAD

**Issue by andris155** [games647/ChangeSkin#224]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
ChangeSkin writes error on Paper 1.17.

### What behaviour is expected:
[//]: # (What did you expect?)
ChangeSkin no writes error on Paper 1.17.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Use Changeskin on 1.17 Paper.

### Plugin list:
[//]: # (This can be found by running `/pl`)
Plugins (32): Admin-Chat, AuthMe, BetterGUI, ChangeSkin, ChatControlRed, Citizens, CompatNoCheatPlus, ConditionalCommands, CoreProtect, EasySetSpawn, FastLogin, HolographicDisplays, HolographicExtension, ImageMaps, ItemJoin, LPC, LuckPerms, MemoryViewer, Multiverse-Core, NashornPlus, NoCheatPlus, PinPrompt, PlaceholderAPI, PlugMan, ProtocolLib, StaffChat, TAB, Vault, WDLCompanion, WorldBorder, WorldEdit, WorldGuard

### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number, SQLite/MySQL, ...)
Waterfall 1.17-R0.1-SNAPSHOT build 437, SQLite.

### Plugin version:
[//]: # (Don't write latest or the build number with #. #Number is used to reference to other tickets.)
[//]: # (This can be found by running `/version plugin-name`.)
ChangeSkin version 3.1-SNAPSHOT-1b4be18

### Error Log:

https://pastebin.com/kqegWxxH

### Configuration:
[//]: # (Remember to delete any sensitive data)

https://pastebin.com/BdjjK6nX

**Comment by games647** [comment]
Is that the full error?

**Comment by andris155** [comment]
Sorry.
This is the full error:
https://pastebin.com/kqegWxxH

**Comment by games647** [comment]
Should be fixed with 6cdccf736a2d36b63cf4609f364fc34d95227840

**Comment by andris155** [comment]
New error on the new version:
https://pastebin.com/ZuzMVB9n

**Comment by andris155** [comment]
```
[ChangeSkin] Cannot find 1.16x fields
java.lang.NoSuchFieldException: dimensionKey
```

**Comment by andris155** [comment]
Thanks.
