### ISSUE TITLE
Cannot invoke "java.lang.Enum.name()" because "gamemode" is null error

### ISSUE THREAD

**Issue by andris155** [games647/ChangeSkin#226]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)
[//]: # (Existing issues can be upvoted by adding a thumps up reaction to the original post)
The Changeskin bukkit version writes Cannot invoke "java.lang.Enum.name()" because "gamemode" is null error.

### What behavior is observed:
[//]: # (What happened?)
The Changeskin bukkit version writes error.

### What behavior is expected:
[//]: # (What did you expect?)
The Changeskin bukkit version no writes error

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
1. Login to the server.
2. Left from the server.

### Plugin list:
[//]: # (This can be found by running `/pl`)
Plugins (31): Admin-Chat, AuthMe, BetterGUI, ChatControlRed, Citizens, CompatNoCheatPlus, ConditionalCommands, CoreProtect, EasySetSpawn, FastLogin, HolographicDisplays, HolographicExtension, ImageMaps, ItemJoin, LPC, LuckPerms, MemoryViewer, Multiverse-Core, NashornPlus, NoCheatPlus, PinPrompt, PlaceholderAPI, PlugMan, ProtocolLib, StaffChat, TAB, Vault, WDLCompanion, WorldBorder, WorldEdit, WorldGuard

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Waterfall 1.17-R0.1-SNAPSHOT build 437, SQLite.

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
ChangeSkin version 3.1-SNAPSHOT-28a50a8

### Server Log:
[//]: # (No images please - only the textual representation)
https://pastebin.com/xfwYHa5i

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
https://pastebin.com/BdjjK6nX

**Comment by games647** [comment]
Okay, I didn't tested that case.

**Comment by andris155** [comment]
Thanks.
