### ISSUE TITLE
ChangeSkin error on 1.17.1

### ISSUE THREAD

**Issue by andris155** [games647/ChangeSkin#227]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
ChangeSkin writes error on Paper 1.17.1.

### What behaviour is expected:
[//]: # (What did you expect?)
ChangeSkin no writes error on Paper 1.17.1.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Use Changeskin on 1.17.1 Paper.

### Plugin list:
[//]: # (This can be found by running `/pl`)
Plugins (32): Admin-Chat, AuthMe, BetterGUI, ChangeSkin, ChatControlRed, Citizens, CompatNoCheatPlus, ConditionalCommands, CoreProtect, EasySetSpawn, FastLogin, HolographicDisplays, HolographicExtension, ImageMaps, ItemJoin, LPC, LuckPerms, MemoryViewer, Multiverse-Core, NashornPlus, NoCheatPlus, PinPrompt, PlaceholderAPI, PlugMan, ProtocolLib, StaffChat, TAB, Vault, WDLCompanion, WorldBorder, WorldEdit, WorldGuard

### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number, SQLite/MySQL, ...)
Waterfall 1.17-R0.1-SNAPSHOT build 445, SQLite.

### Plugin version:
[//]: # (Don't write latest or the build number with #. #Number is used to reference to other tickets.)
[//]: # (This can be found by running `/version plugin-name`.)
ChangeSkin version 3.1-SNAPSHOT-9fa2f2c

### Error Log:

https://pastebin.com/vyYt4j8x

### Configuration:
[//]: # (Remember to delete any sensitive data)

https://pastebin.com/BdjjK6nX

**Comment by games647** [comment]
Which ProtocolLib version do you use?

**Comment by andris155** [comment]
4.7.0

**Comment by games647** [comment]
Looks more like a bug of ProtocolLib with your Java version. Which one are you using?

**Comment by andris155** [comment]
Java 16.0.1. The Minecraft 1.17.1 only support Java 16 or newer Java versions.

**Comment by games647** [comment]
I reported it, but replaced our usage so it works again.

**Comment by andris155** [comment]
Thanks!
