### ISSUE TITLE
This driver org.sqlite.JDBC is not supported on this platform

### ISSUE THREAD

**Issue by uRyanxD** [games647/ChangeSkin#230]
What behavior is observed:
I just downloaded the latest version of Waterfall, configured everything just right and so on and went to put the plugin on the server, then it gave me the error that is attached to the logs, I learned that there was a change in the SQLite package with the last update so many plugins broke.

Steps/models to reproduce:
Start the server.

Plugin list:
ChangeSkin.

Environment description
Waterfall-1.17.448 - SQLite.

Plugin version or build number (don't write latest):
298.

Server Log:
https://hastebin.com/zeyexizehi.yaml

Configuration:
Standard.

**Comment by games647** [comment]
> I learned that there was a change in the SQLite package with the last update so many plugins broke.

Maybe that was Spigot, but BungeeCord (and Waterfall) doesn't include the driver for SQLite. That's why you got the message to please use MySQL instead.

**Comment by uRyanxD** [comment]
Thanks.
