### ISSUE TITLE
1.7.2  instantSkinChange not work and error

### ISSUE THREAD

**Issue by tuanjr** [games647/ChangeSkin#24]
Changeskin install on bungeecord and every spigot, database is mysql, spigot 1.9.2, protocollib 4.0.1
so instantSkinChange not work, player must relog to update skin.
and, this error appear after run command /skin skin-name:
http://paste.ubuntu.com/17656356/

**Comment by games647** [comment]
Do you updated the bungeecord version?

**Comment by games647** [comment]
My mistake
