### ISSUE TITLE
 No SLF4J providers were found.

### ISSUE THREAD

**Issue by ArikSquad** [games647/ChangeSkin#244]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)
[//]: # (Existing issues can be upvoted by adding a thumps up reaction to the original post)

### What behavior is observed:
Console said that old logger. User Plugin#getLogger

### What behavior is expected:
It shouldn't say it

### Steps/models to reproduce:
just launch it

### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/75741608/152677879-a7d255b1-1058-4ffb-af65-be030baef755.png)

### Plugin list:
Placeholderapi and this plugin

### Environment description
1.18.1 papermc

### Plugin version or build number (don't write latest):
329

### Server Log:
[latest.log](https://github.com/games647/ChangeSkin/files/8009994/latest.log)

### Configuration:
default

**Comment by games647** [comment]
It's because the logging framework failed to setup itself. So you don't see any logging messages from the plugin. Could you try out the build `316` before the fix I tried to integrate.
