### ISSUE TITLE
Cannot invoke "net.minecraft.core.Holder.a()" because "holder" is null

### ISSUE THREAD

**Issue by Lucien2714** [games647/ChangeSkin#247]
normal players can't trigger the commands they will get a message, "I'm sorry, but you do not have the permission to perform this command. Please contact the server administrators if you believe that this is in error."
Config: default
Server: papermc1.18.2 with geyser
I checked the config and I am a little bit confused about it, is there something I didn't config correctly?

**Comment by games647** [comment]
Which server platform do you use? In case of proxies like BungeeCord, you have to give the users the permission on the proxy not like usually on the Spigot server.

**Comment by Lucien2714** [comment]
I am using Papermc with the Geyser plugin for bedrock players to join my server. And I tried the /setskin command as op, every time I will just be kicked out of the server, after rejoining I was able to see my skins changed.

**Comment by Lucien2714** [comment]
> Which server platform do you use? In case of proxies like BungeeCord, you have to give the users the permission on the proxy not like usually on the Spigot server.
I am using Papermc with the Geyser plugin for bedrock players to join my server. And I tried the /setskin command as op, every time I will just be kicked out of the server, after rejoining I was able to see my skins changed.

**Comment by games647** [comment]
Please post the server log for that time.

**Comment by games647** [comment]
Which version of ProtocolLib do you have?

**Comment by Lucien2714** [comment]
v4.8.0, I think it is the latest version
> Which version of ProtocolLib do you have?

**Comment by games647** [comment]
Could you please try it out without Geyser to find out the source.

**Comment by Lucien2714** [comment]
sry I didn't check github yesterday. I tried without Geyser and the problems still exist. Here is my test server(Idk why I couldn't put it on github so I am putting it on google drive). [https://drive.google.com/file/d/1cShPb5QeB6zOBFQirU65gdcXIxEkE03y/view?usp=sharing](download link) btw the server is set to run it 25564 port since my main server was running on 25565.

**Comment by games647** [comment]
Okay found it. The error is from: datafixerupper. So this plugin makes issues here.
