### ISSUE TITLE
Server thread/Warn and Error

### ISSUE THREAD

**Issue by StanPiPJacobs** [games647/ChangeSkin#257]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)
[//]: # (Existing issues can be upvoted by adding a thumps up reaction to the original post)

### What behavior is observed:
[//]: # (What happened?)
Server thread warn and server thread error on /setskin

### What behavior is expected:
[//]: # (What did you expect?)
Skin change

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Simply using the /setskin command

### Screenshots (if applicable)
[//]: # (You can drop the files here directly)
https://i.imgur.com/KuFcbAp.png
https://i.imgur.com/K5zq0dR.png

### Plugin list:
[//]: # (This can be found by running `/pl`)
ChangeSkin, CloudTrade, ProtocolLib, SimpleHomes, SimpleTpa

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Magma 1.12.2 6e0b254b
forge 1.12.2 14.23.5.2859
Mod list: https://i.imgur.com/Y78xhg7.png https://i.imgur.com/2jd7wqH.png

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
3.2-SNAPSHOT-74cfd8b

### Server Log:
[//]: # (No images please - only the textual representation)
https://0x0.st/oVCB.log.zip

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
https://pastebin.com/d1M2xTzN

**Comment by games647** [comment]
>org/magmafoundation/magma/remapper/proxy/ProxyClassWriter

Bug in your server software

**Comment by StanPiPJacobs** [comment]
So this is magma's issue?

**Comment by games647** [comment]
yes

**Comment by StanPiPJacobs** [comment]
Aight thanks
