### ISSUE TITLE
BungeeCord for Sponge

### ISSUE THREAD

**Issue by GershonR** [games647/ChangeSkin#26]
I'm using:
https://www.spigotmc.org/resources/skinrestorer-bungeecord-bukkit-java-7.8006/

On my Bungee to work for non-sponge servers, but it looks like it overrides this plugin which is on Sponge so people can't /changeskin

**Comment by games647** [comment]
Why don't you use ChangeSkin on the other servers too :D Just kinding.

Does it work without BungeeCord?

**Comment by GershonR** [comment]
Umm I don't want to do multuple restarts on the bungeecord because it will kick many people off xD

**Comment by GershonR** [comment]
I think when you do /changeskin it works but when you connect to the proxy bungeecord it overrides it

**Comment by games647** [comment]
I mean only a private server on your desktop computer.

**Comment by GershonR** [comment]
Change skin works fine on the server its just when I added bungeecord today the skins are being conflicted with the 2 plugins

**Comment by games647** [comment]
What do you mean with conflicted?

**Comment by GershonR** [comment]
when you login to the bungeecord proxy that plugin will set your skin for you

**Comment by GershonR** [comment]
I think I will just put this onto all my servers and see how it goes, the other developer seems inactive according to threads, i'll post back results why I try this when most people are off

**Comment by GershonR** [comment]
I have put ChangeSkin.jar in my bungee and set fix skins to true but everyone still shows up as steve, I put it on my server and when I did /changeskin [name] [skin] it just keeps popping up that message and nothing else happens

**Comment by games647** [comment]
Do have SpongePLS installed?

**Comment by GershonR** [comment]
That happened on the regular non-spigot servers that are on bungeecord, I tried to have all servers use ChangeSkin

**Comment by games647** [comment]
Asfaik the bungeecord plugin message channels aren't implemented in Sponge or I didn't found any information about it. And this is necessary for communicating between the BungeeCord version and sponge.

**Comment by GershonR** [comment]
I tried it out for 1.9.4 Sponge but got:
http://pastebin.com/zjJGsnVD

**Comment by games647** [comment]
Fixed

**Comment by games647** [comment]
As instant skin updates doesn't work on Sponge, it's impossible to fix the other issues.
