### ISSUE TITLE
PERMISSION FEATURE REQUEST

### ISSUE THREAD

**Issue by RAZERMC** [games647/ChangeSkin#27]
Let the spigot module handle the permission checking
With this method we eliminate the need to use bungee permission and have more freedom to give permissions per server not all server. We also eliminate the need for sql permissions databases. 
Reason is want to use the plugin via bungeecord and i want a per player permission per server.

Example:
STEPS:
1. players types command 
2. bungeecord module receives command
3. bungeecord module assign an id to the command 
4. bungeecord module save the the username, servername the command came from, command and the id to a cache  
5. bungee module sends playername / command / id to spigot module to check for permission
6. spigot module recieves the playername / command / id and checks if playername has permission node from groupmanager or pex for that command
7. if player has permission node then spigot module send true to bungee module with the command id else send false to bungee module with the command id
8. bungee module listens and receive the command id / permission(true/false)
9. if command id's permission = true bungeecord module finds the command id saved in the cache and let it excecute the command else send message to playernames server "you dont have permission to this command" 
10. bungee module cleans the instance from the cache. 

You can setup a time interval for command expiration if the command does not receive confirmation in 3 seconds then send send message to server source to playername "Command cancelled" and bungee module cleans cache. 

thank you in advance and more support!

**Comment by games647** [comment]
I think I should really change that, because a lot of people are requesting this. Although there are plugins like permissionsexbungee or BungeePerms, people like to have the Bukkit permission a lot more.

**Comment by games647** [comment]
I'll add a configuration option where you can activate permissions checking on the bukkit server.

**Comment by RAZERMC** [comment]
There is now a solution to this problem a plugin called permissionsync but for other servers this will be a great addition thanks
