### ISSUE TITLE
skinupdate <other> with version 1.9

### ISSUE THREAD

**Issue by Augustin37** [games647/ChangeSkin#29]
Hello! When I send /skinupdate player to the console, it tells me that I have to be a player to execute that command :/

```java
04:45:30 [INFOS] CONSOLE executed command: /skinupdate KingTramp
04:45:30 [INFOS] You have to be a player to set your own skin
```

thank you for helping :)

**Comment by games647** [comment]
BungeeCord or Bukkit?

**Comment by Augustin37** [comment]
I'm using BungeeCord (sorry I forgot to mention it)

**Comment by games647** [comment]
Then it's fixed with: https://github.com/games647/ChangeSkin/commit/e3af137b2f28ecba64f44f2854326154bc4061a0

**Comment by Augustin37** [comment]
Thank you ! :D
