### ISSUE TITLE
Plugin doesn't work when stop and start

### ISSUE THREAD

**Issue by altrisi** [games647/ChangeSkin#3]
I'm using Spigot 1.8, and when I stop my server and restart it, skins doesn't load, and if I try to use /setskin [player] again, it only say:
> Queued name to uuid resolve
> UUID was successfull resolved from the player name
> The skin is now downloading

But no finish, and an error is dumped to console:

> [11:41:47] [Craft Scheduler Thread - 2/WARN]: Exception in thread "Craft Scheduler Thread - 2" 
> [11:41:47] [Craft Scheduler Thread - 2/WARN]: org.apache.commons.lang.UnhandledException: Plugin ChangeSkin v0.8 generated an exception while executing task 459
> 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.NoClassDefFoundError: com/google/gson/Gson
> 	at com.github.games647.changeskin.SkinData.serializeData(SkinData.java:124)
> 	at com.github.games647.changeskin.SkinData.<init>(SkinData.java:39)
> 	at com.github.games647.changeskin.Storage.getSkin(Storage.java:199)
> 	at com.github.games647.changeskin.tasks.SkinDownloader.run(SkinDownloader.java:30)
> 	at com.github.games647.changeskin.tasks.NameResolver.run(NameResolver.java:53)
> 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
> 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> 	... 3 more

My server is in offline mode, if it help (i'm premium).

**Comment by games647** [comment]
Spigot is required

**Comment by games647** [comment]
Why do you even still run Craftbukkit? Spigot is nearly the same now. Since the Craftbukkit project is dead, it's continued by the Spigot developers here: https://hub.spigotmc.org/

This means you can use Spigot then too.

**Comment by altrisi** [comment]
Sorry, I said

> I'm using Spigot 1.8,...

**Comment by games647** [comment]
Oh I'm really sorry,

could you post the your plugins list? Another plugin is hiding the embedded libraries.

**Comment by games647** [comment]
What's your build number?

**Comment by altrisi** [comment]
Build number:

> git-Spigot-15fa8e1-17a3db7 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

Plugin list:

> dynmap, WorldEdit, VoidWorld, TuxTwoLib, Buycraft, SpectatorPlus, SimpleMOTD, Multiverse-Core, ProtocolLib, ImageOnMap, PerWorldTab, iConomy, PermissionsEx, Simple-AutoSave, Skins, Multiverse-NetherPortals, CustomJoinItems, Multiverse-Portals, Vault, WorldChat, Actionbar, TitleManager, MultiInv, ChangeSkin, TNTRun, HolographicDisplays, CommandSigns, Citizens, ChestCommands, Quester, CommandNPC, AuthMe, MinigamesLib, MGSkyWars, MGOITC, MGDeathRun, MGSeaBattle

Thanks for helping me.

**Comment by games647** [comment]
Found it. It's not a plugin. It's the server version. They added the library this plugin uses in 1.8.3. Is it possible for you to update to 1.8.3 or higher (e.g. 1.8.8)?

**Comment by altrisi** [comment]
I tried it lots of times, but BuildTools throw an error
(log: 

> BuildTools
> 
> unconfigured@null.spigotmc.org
> Attempting to build version: '1.8.9' use --rev <version> to override
> Could not get version 1.8.9 does it exist? Try another version or use 'latest'
> java.io.FileNotFoundException: https://hub.spigotmc.org/versions/1.8.9.json
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
> 	at org.spigotmc.builder.Builder.get(Builder.java:481)
> 	at org.spigotmc.builder.Builder.main(Builder.java:236)

)

Now I will try to download 1.8.3.
Thanks.

**Comment by altrisi** [comment]
With version 1.8.8 throw another error, and doesn't update.
(log:

> BuildTools
> unconfigured@null.spigotmc.org
> Attempting to build version: '1.8.8' use --rev <version> to override
> Found version
> {
> 	"name": "582",
> 	"description": "Jenkins build 582",
> 	"refs": {
> 		"BuildData": "838b40587fa7a68a130b75252959bc8a3481d94f",
> 		"Bukkit": "01d1820664a5f881665b84b28871dadd132deaef",
> 		"CraftBukkit": "e1ebe524a78e27f6a2829ed4574fded3779094e1",
> 		"Spigot": "e4d4710834f7b292bc496f41f1cf9ac363225c0e"
> 	}
> }
> 
> Pulling updates for C:\Users\altrisis\Desktop\old\server1.8\BuildData\.git
> Successfully fetched updates!
> Checked out: 838b40587fa7a68a130b75252959bc8a3481d94f
> Pulling updates for C:\Users\altrisis\Desktop\old\server1.8\Bukkit\.git
> Successfully fetched updates!
> Checked out: 01d1820664a5f881665b84b28871dadd132deaef
> Pulling updates for C:\Users\altrisis\Desktop\old\server1.8\CraftBukkit\.git
> Exception in thread "main" org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of reset command. {0}
> 	at org.eclipse.jgit.api.ResetCommand.call(ResetCommand.java:230)
> 	at org.spigotmc.builder.Builder.pull(Builder.java:515)
> 	at org.spigotmc.builder.Builder.main(Builder.java:257)
> Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock C:\Users\altrisis\Desktop\old\server1.8\CraftBukkit\.git\index
> 	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
> 	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
> 	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
> 	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
> 	at org.eclipse.jgit.api.ResetCommand.checkoutIndex(ResetCommand.java:390)
> 	at org.eclipse.jgit.api.ResetCommand.call(ResetCommand.java:203)
> 	... 2 more

)
Thanks (another time)

**Comment by games647** [comment]
Do you tried to start in a clean folder?

**Comment by altrisi** [comment]
No, because I don't know if ALL my plugins, config, worlds, arenas,... will work in a new folder.

I will try it.

Thanks.

**Comment by games647** [comment]
I thought about just building the server there and then copy it.

**Comment by altrisi** [comment]
Reolved. Thanks.
