### ISSUE TITLE
BungeeCord command redirection

### ISSUE THREAD

**Issue by Augustin37** [games647/ChangeSkin#32]
Hello I have a question, I don't know if this is possible but:
We can't type "/setskin", or "/skinupdate" from the console of a subserver when we have BungeeCord set, we have to do it from the bungee console. I want to know if it could be possible to redirect the command directly to the bungee console (like when we do the command in game) when typing it on any bungee subserver console?

I want this feature because I'm using JSONAPI to communicate between my website and my server, only JSONAPI can only communicate with a subserver (it is not compatible with Bungee). Currently I'm using an extra plugin to transfer the command but it's not very optimized. I don't know if it is clear :confused: 

By the way I wanted to thank you very much for this plugin which is a lot more stable than SkinsRestorer! :)

**Comment by games647** [comment]
>By the way I wanted to thank you very much for this plugin which is a lot more stable than SkinsRestorer! :)

First of all, thank you very much ^^

Ouh, do you need the result of the command too?

>an extra plugin to transfer the command but it's not very optimized

Which plugin do you currently use?

**Comment by Augustin37** [comment]
> Ouh, do you need the result of the command too?

It would be cool but it is not necessary :)

I am currently using [CommandSync](https://www.spigotmc.org/resources/commandsync.115/) but I am using it only for ChangeSkin so.. ^^

I saw that you just added the feature! Thank you very much you are fast!! :D
