### ISSUE TITLE
/skinupdate & /skin reset

### ISSUE THREAD

**Issue by Luuzzi** [games647/ChangeSkin#33]
Hello. I found bug. When i use /skinupdate, skin not updated, and when i reset skin (/skin reset) skin too not updated. She remains same, when i set. l'm doing something wrong?

http://pastebin.com/reRJ5Bws

**Comment by Luuzzi** [comment]
As I can see ID in the database does not change, when i used command.

**Comment by games647** [comment]
Which version do you use?

**Comment by Luuzzi** [comment]
Last

**Comment by games647** [comment]
Do you use BungeeCord?

**Comment by Luuzzi** [comment]
Yes.

**Comment by games647** [comment]
>And information in skinData has duplicate

because it could be a updated skin

>As I can see ID in the database does not change,

The id in the skindata will never change. Take a look at the preferences table.

Is your server in online mode with premium UUIDs?

**Comment by games647** [comment]
>ava.io.IOException: Server returned HTTP response code: 429 for URL: https://sessionserver.mojang.com/session/minecraft/profile/6fee352611444731b57d4b89eb0d466f?unsigned=false

This means the skin was requested too many times. So it's ignored.

Do you have ChangeSkin instaled on the Bukkit server?

**Comment by Luuzzi** [comment]
Offline mode. ChangeSkin on bukkit server? No.

**Comment by games647** [comment]
That's necessary for skin updates without relogging. On the project site of Spigot is a little on how to do it.
