### ISSUE TITLE
MySQL request error.

### ISSUE THREAD

**Issue by Luuzzi** [games647/ChangeSkin#34]
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UNSIGNED INTEGER PRIMARY KEY AUTO_INCREMENT, `Timestamp` BIGINT NOT NULL, `UUID`' at line 1
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
    at com.mysql.jdbc.Util.getInstance(Util.java:360)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
    at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1618)
    at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1549)
    at com.github.games647.changeskin.core.SkinStorage.createTables(SkinStorage.java:85)
    at com.github.games647.changeskin.bungee.ChangeSkinBungee.onEnable(ChangeSkinBungee.java:89)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:157)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:209)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:33)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:12)

**Comment by games647** [comment]
Could me send me your config?

**Comment by Luuzzi** [comment]
# ChangeSkin config

# Here you can specify default skins for player who do not have a skin
# The entries from this list will be selected in random order
#
# Lists are created like this:
#default-skins:
#    - 0aaa2c13-922a-411b-b655-9b8c08404695
#    - 069a79f4-44e9-4726-a5be-fca90e38aaf5
#
# If this list is empty no skin will be selected
default-skins: []

# If the player does not have a skin and hasn't chosen one with /setskin
# this will try to redownload using the username of the player
restoreSkins: true

# Should the skins apply instantly without relogins
# The player will be invisible for a shorten time
instantSkinChange: false

# Should the plugin check for skin specific permissions nodes like
# changeskin.skin.whitelist.uuid
# changeskin.skin.whitelist.* allows all skins
#
# The plugin checks only if the player has one of these and will not check all of them
# Examples:
#   Whitelist:
#       Give the players the permission changeskin.skin.whitelist.uuid
#       or changeskin.skin.whitelist.* for all skins
#
#   Blacklist:
#       Give your players this permission changeskin.skin.whitelist.*
#       and a negative (- before the permission) permission: '-changeskin.skin.whitelist.uuid'
#       |-> This means all skins are allowed except the ones with the uuid in the blacklist list
skinPermission: false

# A number in seconds which the player have to wait before changing the skin again
cooldown: 0

# How many requests should be established until the plugin uses the third-party API https://mcapi.ca/
# Once this number is reached in a range of ten minutes it will start connecting to https://mcapi.ca/ for the next ten minutes
# This option exists in order to workaround the rate-limiting. Name -> UUID are fetched in the same way like heads
mojang-request-limit: 600

# In order to use a skin, the player name have to be resolve to the UUID and then have to be downloaded using the UUID.
# Both requests are rate-limited. The first request is 600 requests per 10 minutes. The second one is rate-limited with
# one request per indivual skin per minute. So unlike the name resolve there cannot be two requests for the
# same skin within one minute.
#
# This might conflict with some heads plugins. Due this stricter rate-limiting this feature is added.
# The option above is for name resolving while this is only for skin downloading.
#
# This feature makes use of https://mcapi.de/. If you actively use this feature, please support the author.
independent-skin-downloading: false

# Only relevant for BungeeCord
# Here you can ignore certain servers in order to make use of lazy loading -> load the player data only
# if they are on the allowed servers
#
# This can be used against bot attacks
# If this is empty, nothing will be ignored
server-blacklist: []
# Lists are created like this:
#server-blacklist:
#    - pvp
#    - lobby

# If you have a BungeeCord server, this option might be relevant for you.
# If you activate this option, the permission will be checked on the bukkit server and only on the bukkit server.
#
# This requires to install the plugin on the bukkit server too in order to send the response to the bungeecord server
#
# You still have to give the users the permission on the BungeeCord server in order to execute the command, but the bukkit
# server will verify if the user has the permissions on the backend server too.
bukkit-permissions: false

# Database configuration
# Warning: If you use BungeeCord, you should switch to MySQL, because BungeeCord has only a driver for MySQL
storage:
    driver: com.mysql.jdbc.Driver
    host: 127.0.0.1
    port: 3306
    database: Skins
    username: root
    password: qwerty

**Comment by Luuzzi** [comment]
http://pastebin.com/LmmvcrDB

**Comment by Luuzzi** [comment]
i need to update MySQL server?
