### ISSUE TITLE
Add skins to tab

### ISSUE THREAD

**Issue by TrademarkTM** [games647/ChangeSkin#38]
**This is not an issue**

Hi!
Your plugin is really nice, but I want to request one thing. It doesn't fix the skins in TAB. So there's no player heads. Example: http://prntscr.com/bwxrva (in a cracked server which it works).

Could you add it?

Thanks!

**Comment by games647** [comment]
That example server doesn't seem to be cracked. I didn't found a way to do it without modifying the online mode.
