### ISSUE TITLE
[Feature request] Automatic skin update with ignore rule

### ISSUE THREAD

**Issue by Augustin37** [games647/ChangeSkin#39]
Hello! I wanted to know if you could add an automatic skin update function? Like if the skin last download is more than 24h, it updates it. A lot of players aren't aware of the /skinupdate command and finaly they think that it's a bug.

Also, can you add a flag to the /setskin command to keep a snapshot and to forbid the skin to update if players don't want their skin to change?
something like :
> /setskin player1 player2 -p

Thank you very much ! :smiley:

**Comment by games647** [comment]
FYI: I'm putting this on hold until I finished the skin uploading.

Automatically updates wouldn't be so complicated, but the ignore rule is.
