### ISSUE TITLE
Skins stop working on server restart

### ISSUE THREAD

**Issue by FiranWolf** [games647/ChangeSkin#4]
When I first added the plugin, everything worked perfectly, skins loaded with no problems. Though, now that I restarted the server, skins don't load anymore. I run an offline Spigot 1.9 server.

I have noticed that if I stop the server, delete the "ChangeSkin.db" file, and start it again, the plugin works just as well as the first time I ran it. But I don't want to delete that file every time I have to restart the server, as it gets annoying.

I use the plugin version 0.8, because version 0.9 throws an error.
v 0.9 error: http://hastebin.com/eyatodemaj.sm

**Comment by games647** [comment]
>But I don't want to delete that file every time I have to restart the server, as it gets annoying.

Of course. 

The problem is that. Version 0.9 expects a Spigot servers, but you are running craftbukkit.

**Comment by games647** [comment]
I guess the changes I made will fix it. I'll upload it today after some tests.

**Comment by FiranWolf** [comment]
Oh wow, sorry about that, I thought I was using spigot, but a closer look at the logs show I had been using CraftBukkit all along. I'll switch over to Spigot right away

**Comment by games647** [comment]
Do you still have the issue?

**Comment by FiranWolf** [comment]
Yeah, and it also seems to happen when I use a MySQL database instead of the SQLite storage.

**Comment by games647** [comment]
Any errors?

**Comment by FiranWolf** [comment]
None

**Comment by games647** [comment]
Found the issue. I'll fix it.

**Comment by games647** [comment]
Sorry I didn't noticed that earlier.

**Comment by FiranWolf** [comment]
No worries! Can you link me to the fixed version?

**Comment by games647** [comment]
https://www.spigotmc.org/resources/changeskin.21469/update?update=87061

**Comment by FiranWolf** [comment]
Thanks for the link, although it still doesn't work

**Comment by games647** [comment]
Oh, I forgot to say that I changed the table setup. You should regenerate the table.

**Comment by FiranWolf** [comment]
I tested it this morning, and it still isn't working. I tried the plugin with SQLite and MySQL, both have the same problem.

**Comment by games647** [comment]
Oh, I'm really sorry. I created this issue by fixing #5. I fixed it now. I'll upload a new version right away.

**Comment by FiranWolf** [comment]
No worries! Just send me the link and I'll try it out!

**Comment by games647** [comment]
Update is uploaded.

https://www.spigotmc.org/resources/changeskin.21469/update?update=87369

I hope it works now for you.

**Comment by FiranWolf** [comment]
It still doesn't work, with both MySQL or SQLite

**Comment by games647** [comment]
Do you regenerated the table?

**Comment by FiranWolf** [comment]
Yeah, I deleted them before testing

**Comment by games647** [comment]
It works now absolutely fine for me. Does the skin apply if you invoke /setskin <player>?

**Comment by FiranWolf** [comment]
I can change to any skin that is not already in the database, but not those that have been downloaded already

**Comment by games647** [comment]
I should have fixed this in 0.9.3. Do you have this effect only after server restarts or do you just receive no new skin if you invoke that command?

**Comment by FiranWolf** [comment]
Only after server restarts. Like, if I remove the tables in the database, everything works, until I restart the server.

**Comment by games647** [comment]
Could I get the startup log?

**Comment by FiranWolf** [comment]
https://gist.github.com/FiranWolf/0b8bac92ea827847ff9974c6c50e474f

**Comment by games647** [comment]
Do you receive an empty skin or keep your old one?

Sorry for all the questions. I thought I fixed it in 0.9.3. After that update I cannot longer reproduce this issue.

**Comment by FiranWolf** [comment]
Well I don't really know if it's an empty skin. It's the default Steve skin, and not my own.

No worries, I'll help however I can!

**Comment by games647** [comment]
Does it happen only to you? Which skin do you try?

**Comment by FiranWolf** [comment]
I'm not sure if it's only with me, I will check a little later with a friend, though I think it's everyone. I try my own skin, and other random skins. Like I said, if I delete the tables before restarting the server, any skin works

**Comment by FiranWolf** [comment]
So it only seems to be happening to me, but I don't know what could be causing it. I have a valid Minecraft account and everything with a skin.

**Comment by games647** [comment]
Found it. You use a different skin model.

**Comment by FiranWolf** [comment]
So is there a way to fix that? Should I use the Steve template, or the Alex template?

**Comment by games647** [comment]
Yes I'll fix that.

**Comment by FiranWolf** [comment]
Ohh, I thought I needed to change my skin model or something. But let me know when it's fixed, I'll try it out!

**Comment by games647** [comment]
Do you changed your skin?

**Comment by FiranWolf** [comment]
I tried using a random skin and everything works fine, so I'm really not sure what's wrong with my skin

**Comment by FiranWolf** [comment]
Thanks a lot for all the fixes, everything is now working great!
