### ISSUE TITLE
Items of player delete when changes skin

### ISSUE THREAD

**Issue by xeonentr** [games647/ChangeSkin#40]
Problem is this. I described on title. Sorry for bad English.

**Comment by games647** [comment]
What plugins do you use?

What mc version do you use?

**Comment by xeonentr** [comment]
Server Version : 1.8.8 paperspigot

Plugins :
AAC alphachest antijoinbot antispam auctionhouse authme autorank changeskin chestcommands chestshop citizens clearchat clearlag combattracker deathmessages essentials factions featherboard frameprotect groupmanager hideandcustomplugins holographicdisplays iconomyrecreation namebugfixed itemcases letitrain lockette massivecore mineresetlite multiversecore mvdwplugin mythicmobs plotsquared protocollib pluginmetrics scheduledannouncer2 serverlistmotd shopkeepers simplevipperks stats tabprefixes timtheenchanter titlemanager vault worldedit worldguard

**Comment by games647** [comment]
what authme version do you use?

**Comment by xeonentr** [comment]
i think 3.5 snapshot

**Comment by games647** [comment]
Could you make a "/protocol dump" ?

**Comment by xeonentr** [comment]
http://hastebin.com/cuyotawusa.sm

**Comment by games647** [comment]
And when does it happen? Is a different inventory open in the meanwhile?

**Comment by xeonentr** [comment]
i didnt see that problem. A player of our server said. A reliable player.

**Comment by xeonentr** [comment]
I think inventory of the skin he changed to opened.

**Comment by games647** [comment]
Which build of PaperSpigot do you use?

**Comment by xeonentr** [comment]
This server is running CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by games647** [comment]
Could you try this one: https://github.com/games647/ChangeSkin/releases/tag/inventory 

please?

**Comment by xeonentr** [comment]
I think, it's fixed. And thanks for your help, sorry for bad English. I want to all developers to help me like you :)

**Comment by games647** [comment]
Looks like it actually was a bug in Spigot

see here:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/1e4dd71cf216f953a00e1a82901703b39b84ee6e
