### ISSUE TITLE
Some new peoples get wrong skin

### ISSUE THREAD

**Issue by xion87** [games647/ChangeSkin#41]
Latest bungeecord
Server 1.8.8
Changeskin 2.2.1 installed on bungeecord and hub

Some new-joined poeple are complaining that they have empy skin or random skin and they are not registred in the mysql database, is fixable only with /skin name name by a staff, /skinupdate will not help to fix it. I already reported the issue on pm but seem to be not resolved :(

**Comment by xion87** [comment]
Sorry, yes i am Malachiel, I dind't tested if that issue still persist (about players changing my skin), i have to disable autoskinupdate on bungeecord and enabled it on hub server?

**Comment by games647** [comment]
>i have to disable autoskinupdate on bungeecord and enabled it on hub server?

Actually not. Just report if it happens again.

**Comment by xion87** [comment]
it happen again for some users

**Comment by games647** [comment]
What does the database entries looked like?
