### ISSUE TITLE
error - AsyncPlayerPreLoginEvent

### ISSUE THREAD

**Issue by mat41997** [games647/ChangeSkin#45]
logs
http://pastebin.com/YjyXBcm1

timings
https://timings.aikar.co/v2/?id=d8e3bbc08a2f40d284624d6bab57a191

**Comment by games647** [comment]
There should be an error before that one.

**Comment by mat41997** [comment]
http://pastebin.com/0kgSfgsV

**Comment by games647** [comment]
>Connection is not available, request timed out after 30000ms.

Your database is down.

**Comment by mat41997** [comment]
ok thx ^^
