### ISSUE TITLE
Cannot upload skins

### ISSUE THREAD

**Issue by friishon** [games647/ChangeSkin#46]
when i try to upload a skin with the commands /skinupload http://imgur.com/a/oB9zT i have this error
"An internal error ocurred while attempting to perform this command"
and i can't wirte command skinname because i have and error on my console
skin select don't work 

/skinupldate:
![captura de pantalla - 290816 - 13-08-15](https://cloud.githubusercontent.com/assets/19889173/18049710/2811e7d0-6dea-11e6-824e-0ae24db20941.png)

/skinname
![captura de pantalla - 290816 - 13-09-38](https://cloud.githubusercontent.com/assets/19889173/18049711/2812538c-6dea-11e6-9468-e75be5a6cd77.png)

thanks about the plugin

**Comment by games647** [comment]
Do you use BungeeCord?

**Comment by games647** [comment]
Try to use skin-upload

**Comment by friishon** [comment]
yes i'm using bungeecord and when i write /skin-upload http://imgur.com/a/08O51
nothing happends
when i write /skin-name or skinname i have the same error

**Comment by games647** [comment]
Skin name isn't implemented/supported as you can see in the error. 

The url isn't a raw image file. Please use the direct link.
https://i.imgur.com/Oc3hacu.png

**Comment by friishon** [comment]
/skin-upload https://i.imgur.com/Oc3hacu.png
don't work
:(

**Comment by games647** [comment]
Please explain it more. Error message?

**Comment by friishon** [comment]
when i write this command, nothing it happend the command don't work
![tnt](https://cloud.githubusercontent.com/assets/19889173/18089174/e541fbae-6ebe-11e6-81b4-cc66304f5f22.PNG)
when i write /skinupdate i have this error here
![tnt2](https://cloud.githubusercontent.com/assets/19889173/18089187/014a14ee-6ebf-11e6-9e43-726b956ffc53.PNG)
and in the console i have it
![error skin](https://cloud.githubusercontent.com/assets/19889173/18089223/1f406a52-6ebf-11e6-8bec-844797d15e97.png)

**Comment by games647** [comment]
I need the startup log too.

**Comment by games647** [comment]
Do you installed it on BungeeCord too?

**Comment by friishon** [comment]
yes i have installed on bungeecord

**Comment by games647** [comment]
>I need the startup log too.

**Comment by friishon** [comment]
**bungee startup**
![bun1](https://cloud.githubusercontent.com/assets/19889173/18111650/bc585ba8-6f21-11e6-854c-d7c599881b71.png)
![bun2](https://cloud.githubusercontent.com/assets/19889173/18111655/c18a2e6c-6f21-11e6-9c19-bde13583cdb7.png)

**spigot startup**
![cap1](https://cloud.githubusercontent.com/assets/19889173/18111684/e9e623d4-6f21-11e6-9c08-3bb9a1ca13d0.png)
![cap2](https://cloud.githubusercontent.com/assets/19889173/18111685/e9ea3460-6f21-11e6-84b1-d9bb30ada774.png)
![cap3](https://cloud.githubusercontent.com/assets/19889173/18111687/e9ef1886-6f21-11e6-8aaf-b8808e83e8eb.png)
![cap4](https://cloud.githubusercontent.com/assets/19889173/18111686/e9eb4e40-6f21-11e6-9dd9-410e66de5a72.png)

**Comment by games647** [comment]
I don't see a message in BungeeCord that says that an account was authenticated. Do you specified an account in the bungee config of ChangeSkin?

**Comment by friishon** [comment]
this is my config
storage:
# Single file SQLite database
    #driver: org.sqlite.JDBC
    # File location
    #database: '{pluginDir}/ChangeSkin.db'

# MySQL
     driver: com.mysql.jdbc.Driver
     host: 192.168.1.xx
     port: 3306
     database: ChangeSkin
     username: user
     password: password

**Comment by games647** [comment]
No an upload account.

**Comment by friishon** [comment]
where i have it?

**Comment by friishon** [comment]
i have only on spigot server?? or i have un bungee and  spigot??

**Comment by games647** [comment]
https://github.com/games647/ChangeSkin/blob/master/core/src/main/resources/config.yml#L69-80

**Comment by games647** [comment]
It's required to upload skins.

**Comment by friishon** [comment]
#  Example:
#  upload-accounts:
#     - EMAIL:PASSWORD
#     - EMAIL:PASSWORD
upload-accounts: 
      -mail@mail.com:password (minecraft password??)


that config??

**Comment by games647** [comment]
Yes. Do you specified an account there, because I didn't saw any "authenticated .. "-message.

**Comment by friishon** [comment]
how many account i have to put there??
only mine? or other acount?

**Comment by games647** [comment]
One is enough. The rate-limit from mojang limits for one upload per minute per account.

**Comment by friishon** [comment]
all skin will upload on my account?

**Comment by games647** [comment]
Yes, but every time it will be reverted to your old skin. So basically:

1. Download skin
2. Change skin to the url specified one
3. Download the new skin
4. Change it back
