### ISSUE TITLE
"default skin" work only sometimes, no errors

### ISSUE THREAD

**Issue by xion87** [games647/ChangeSkin#49]
hi i seetted like this the config:
default-skins:
    - 293364af-825b-4ab9-8702-7d85dee891a7

I still see some steeves and alex in my server, instead for other people it work, no errors on log

**Comment by games647** [comment]
Could you send the the names of those players?

**Comment by xion87** [comment]
therese players are the buged player without skin, they fixed it with /skinupdate

**Comment by games647** [comment]
Then it's related to the other ticket.
