### ISSUE TITLE
NullPointerException SkinUpload

### ISSUE THREAD

**Issue by cmisztur** [games647/ChangeSkin#52]
Hello, skinupload does not work.  Any ideas how to get more info?

> Spigot 1.10
> 
> ChangeSkin: Successfull authenticated user 74c62b3a4bff
> 
> 1:57:01 PM CONSOLE: [INFO] TATODOG issued server command: /skinupload http://www.minecraftskins.com/thumbnails/technoblox-9873879.png
> 1:57:02 PM CONSOLE: WARN]: Exception in thread "Craft Scheduler Thread - 13"
> 1:57:02 PM CONSOLE: WARN]: org.apache.commons.lang.UnhandledException: Plugin ChangeSkin v2.3.2 generated an exception while executing task 3110

**Comment by games647** [comment]
I need the full stacktrace

**Comment by cmisztur** [comment]
`[13:55:22] [Craft Scheduler Thread - 12/WARN]: org.apache.commons.lang.UnhandledException: Plugin ChangeSkin v2.3.2 generated an exception while executing task 1839
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.net.URLEncoder.encode(Unknown Source)
	at com.github.games647.changeskin.core.MojangAuthApi.changeSkin(MojangAuthApi.java:90)
	at com.github.games647.changeskin.bukkit.tasks.SkinUploader.run(SkinUploader.java:48)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more`

**Comment by games647** [comment]
The skinUrl is invalid. You need the raw skin file not the rendered one.

**Comment by games647** [comment]
And what's the username of your uploader account?

**Comment by cmisztur** [comment]
The MC username is TATODOG with email chris at chrismisztur dot net.

I looked at the source and it points back to this, right?

> String oldSkinUrl = plugin.getCore().getMojangAuthApi().getSkinUrl(profile.getName());

**Comment by games647** [comment]
Yes and that is null, because the header field Location (for redirection) was available.

**Comment by games647** [comment]
I guess profile.getName() returned an invalid username.

**Comment by cmisztur** [comment]
Anything I could try on my side?

**Comment by games647** [comment]
Yes, could you try the latest dev-build?

**Comment by cmisztur** [comment]
do you have the bits or do I have to build?

**Comment by games647** [comment]
https://github.com/games647/ChangeSkin/releases/tag/upload-debug

**Comment by cmisztur** [comment]
"/skinupload url" returns a successful response, however skin selection only works for skins uploaded directly on minecraft.net.  "/skinselect 12" returns a success message, however the skin shown is the last skin uploaded on minecraft.net

> 
/skinupload http://imgur.com/a/FFwWE
issued server command: /skinselect 12

**Comment by games647** [comment]
You have to use https://i.imgur.com/VpEebg9.png not  http://imgur.com/a/FFwWE

**Comment by games647** [comment]
You have to use https://i.imgur.com/VpEebg9.png not  http://imgur.com/a/FFwWE
