### ISSUE TITLE
disappearing blocks

### ISSUE THREAD

**Issue by DoreK333** [games647/ChangeSkin#58]
بعد تثبيت هذا البرنامج المساعد تختفي جميع الكتل بعد خروج والدخول إلى الملقم.
http://imgur.com/a/hCZG9
I would recommend Google Translator

**Comment by games647** [comment]
What's your minecraft version?

**Comment by Dorii2003** [comment]
1.11.2

**Comment by games647** [comment]
Do you use BungeeCord/Spigot/Bukkit or Sponge?

**Comment by Dorii2003** [comment]
PaperSpigot

**Comment by mat41997** [comment]
timings
https://timings.aikar.co/?id=893a6759d66b41e48388ad7e518b05eb

**Comment by games647** [comment]
@Dorii2003 Do you use a custom client or the vanilla (mojang without mods) one?

**Comment by Dorii2003** [comment]
Optifine+Chocapic13's shaders V6 Lite

**Comment by games647** [comment]
@Dorii2003 Which plugin version do you use?

**Comment by games647** [comment]
Try this one: [chunk-loading](https://github.com/games647/ChangeSkin/releases/tag/chunk-loading)

**Comment by Dorii2003** [comment]
Same ;/

**Comment by games647** [comment]
Uploaded a new version same link.

**Comment by mat41997** [comment]
same : /
![2017-02-25_15 35 16](https://cloud.githubusercontent.com/assets/5884000/23332000/26ae4144-fb71-11e6-916e-ab2556a437ec.png)
![2017-02-25_15 42 48](https://cloud.githubusercontent.com/assets/5884000/23332006/3c27ab3c-fb71-11e6-8807-7556ca705480.png)

**Comment by aescraftbr** [comment]
press F3+A.

**Comment by mat41997** [comment]
f3+a not work
