### ISSUE TITLE
mysql mariadb | bungeecord waterfall | error log

### ISSUE THREAD

**Issue by mat41997** [games647/ChangeSkin#59]
changeskin version
https://github.com/games647/ChangeSkin/releases/tag/chunk-loading

waterfall version
https://ci.destroystokyo.com/job/Waterfall/101/

logs
https://gist.github.com/mat41997/1c281d9736be11854aaba8bd13f48525

config
https://gist.github.com/mat41997/3cd34fe1dadfa7e9c21bbe3ff75e0c5b

**Comment by games647** [comment]
>Access denied for user 'root'@'localhost' (using password: NO)

At least read your logs next time.

**Comment by mat41997** [comment]
ok, i fix it
https://gist.github.com/mat41997/43fb08db893919502b8434726c6b719b

thx. for the help
