### ISSUE TITLE
permissions not work

### ISSUE THREAD

**Issue by mat41997** [games647/ChangeSkin#6]
player not can change skin

only admin can change the skin

java 8
PaperSpigot 1.9.2

permissions
    - changeskin.skin.*
    - changeskin.skin.playerName
    - changeskin.skin.uuid
    - changeskin.command.setskin

logs on client
[19:19:18] [Client thread/INFO]: [CHAT] I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.

logs on console
[19:18:13] [Server thread/INFO]: mtqsen issued server command: /skin QiiQii

i not can change my skin

**Comment by games647** [comment]
Have your players also the permission: ChangeSkin.command.setskin

**Comment by games647** [comment]
Ah, this looks the message from Bukkit. Try out if the following permission works:

changeskin-parent.command.setskin

**Comment by mat41997** [comment]
Yes, its works, thanks ^^

**Comment by games647** [comment]
The last one?

**Comment by mat41997** [comment]
why?

**Comment by games647** [comment]
I mean which permission node fixed the issue?

**Comment by mat41997** [comment]
changeskin-parent.command.setskin

problem has fixed, thanks ^^

**Comment by games647** [comment]
np. Sorry for all the issues you had recently.

**Comment by mat41997** [comment]
sorry, i not understand XD
