### ISSUE TITLE
Permissions Problem

### ISSUE THREAD

**Issue by Bodyash** [games647/ChangeSkin#61]
I`m Using Bungeecord.
My Bungeecord Permissions:
```
permissions:
  default:
  - changeskin.*
  - changeskin.skin.whitelist.*
  - changeskin.command.*
  - changeskin.command.setskin.other
  - changeskin.command.skinupdate
  - changeskin.command.skinupload
  - changeskin.command.skinname
  - changeskin.command.skinselect
  - changeskin.command.skinupdate.other.*
  - changeskin.command.setskin
  - bungeecord.command.list
````
ChangeSkin configured to CHECK permissions on Bukkit server.
So here is my PEX permissions:
```
  Member:
    permissions:
    - -changeskin.command.setskin
    - changeskin.*
    - changeskin.skin.*
```

All Permissions and Negated /setskin permission. But players cant use /skinupdate, while they dont have permissions to /setskin command. Can u fix this?

**Comment by games647** [comment]
Fixed. Now it checks only the whitelist permission
