### ISSUE TITLE
Jenkins build

### ISSUE THREAD

**Issue by sgdc3** [games647/ChangeSkin#62]
http://ci.xephi.fr/job/ChangeSkin/
;)

**Comment by games647** [comment]
Thanks. Should I install a commit hook for you?

**Comment by sgdc3** [comment]
Nope, it should detect any changes automatically (I used SCM pooling)

**Comment by games647** [comment]
>Nope, it should detect any changes automatically (I used SCM pooling)

Could you do the same for FastLogin? It appears it only builds on AuthMe changes
