### ISSUE TITLE
[Question] Port used by ChangeSkin

### ISSUE THREAD

**Issue by xion87** [games647/ChangeSkin#63]
Plating with firewall and anaylizing trafic i noticed the plugin is spamming continuing connection to port 53, instead blocking port 53 it block skin set functionality, why?

**Comment by games647** [comment]
Outgoing or target port?

**Comment by xion87** [comment]
nvm i just found that traffic was blocked because of my ovh firewall and don't from cisco and is that why i got a lot of spam from port 53
