### ISSUE TITLE
Server blacklist will never "unload" a loaded skin

### ISSUE THREAD

**Issue by xion87** [games647/ChangeSkin#69]
Hi, i would like to have the feature to "unload" the skin if a user enter in a blacklisted server and load the skin again when you quit from it (i am using changeskin on bungee)
I would need this feature because i got a murder server and i  don't want skin be seen in this special server

**Comment by xion87** [comment]
any news about it?

**Comment by games647** [comment]
Do have the bukkit module installed on that server?

**Comment by xion87** [comment]
i tried with it, and without it, it still load

**Comment by games647** [comment]
If you join directly to this server or if you switch the servers.

**Comment by xion87** [comment]
when i switch it, is a server under bungee

**Comment by games647** [comment]
It's because the skin is already loaded, so ChangeSkin doesn't interact with the player at all.

**Comment by xion87** [comment]
So any solution about hide the skin or apply a certain skin for this game?

**Comment by games647** [comment]
I could write something that clears the skin properties if you join that server.

**Comment by xion87** [comment]
i would like if you do it :)
