### ISSUE TITLE
You can add a white-list and a black-list for skins list?

### ISSUE THREAD

**Issue by mat41997** [games647/ChangeSkin#7]
: )

add the new function to legal skin, and no-legal skin, and permissions for this

on config, config ChangeSkin plugin

white-list-skins: 
    - b500f8be-72b5-42e7-a105-d18f916a324f

black-list-skins: 
    - 8049614c-496a-4f37-9246-9f70cad6e863

you can add this function and baypass permissions for this

on permissions plugin, permissions
- ChangeSkin.permitted.skin.b500f8be-72b5-42e7-a105-d18f916a324f
- ChangeSkin.prohibited.skin.8049614c-496a-4f37-9246-9f70cad6e863

**Comment by mat41997** [comment]
and command
/SkinBan SkinName/UUID
/SkinAddToWhiteList SkinName/UUID

**Comment by games647** [comment]
I added only permissions, because I think it's better to handle those through different permission groups.

Here is an example of how to use it.
https://github.com/games647/ChangeSkin/blob/master/core/src/main/resources/config.yml#L29

**Comment by mat41997** [comment]
thanks

**Comment by mat41997** [comment]
ymm you can change

default permissions:
- changeskin.command.setskin.other.* 
- changeskin.command.setskin 
- changeskin.command.setskin.other

blacklist permissions
- -changeskin.command.setskin.other.8049614c-496a-4f37-9246-9f70cad6e863
- -changeskin.command.setskin.8049614c-496a-4f37-9246-9f70cad6e863

whitelist permissions
- changeskin.command.setskin.other.b500f8be-72b5-42e7-a105-d18f916a324f
- changeskin.command.setskin.b500f8be-72b5-42e7-a105-d18f916a324f


you can understand this idea? 
sorry for my not good english : P

**Comment by games647** [comment]
You mean the negative permissions ('-')?

**Comment by mat41997** [comment]
yes

**Comment by games647** [comment]
That's not possible while having a whitelist and blacklist at the same time.

**Comment by mat41997** [comment]
yes of course

**Comment by mat41997** [comment]
the idea

== change format ==

= the white list - replce =
to
# - changeskin.skin.whitelist.uuid
# - changeskin.skin.whitelist.* allows all skins
change to
# - changeskin.command.setskin.other.uuid
# - changeskin.command.setskin.other.*  allows all skins
# - changeskin.command.setskin.uuid
# - changeskin.command.setskin.*  allows all skins

= the black list - replace =
and to
# - changeskin.skin.whitelist.*
# - changeskin.skin.blacklist.uuid
change to
# - -changeskin.command.setskin.*
# - -changeskin.command.setskin.uuid
# - -changeskin.command.setskin.other.*
# - -changeskin.command.setskin.other.uuid

  |
  |
 \ /
# - -

**Comment by mat41997** [comment]
understand me?

**Comment by games647** [comment]
That won't work. The negative blacklist permissions ('-changeskin.command.setskin.*') would override the whitelist. Then your cannot use any skin.

**Comment by mat41997** [comment]
aaaa ok : P

I wanted good

**Comment by mat41997** [comment]
Anyway, thank you.
good job XD
