### ISSUE TITLE
ChangeSkin - BungeeCord + Spigot 1.8.8

### ISSUE THREAD

**Issue by Spikey101** [games647/ChangeSkin#74]
Hello,
I am using ChangeSkin with BungeeCord and Spigot 1.8.8, I put the jar file in my BungeeCord directory, and each of my Spigots directory. I set it up so that they all connect to the same MySQL database, I start the server, Join the game and try setting a skin. I will get the message in game saying blah blah you're skin is being downloaded and it seems okay, but my skin never gets updated. So I look in the console, and I have an error only in my BungeeCord Console.

``
03:31:34 [FINE] [ChangeSkin] Making UUID->Name request for sloth
03:31:36 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@4d02f94e, id=47, owner=com.github.games647.changeskin.bungee.ChangeSkinBungee@1654a892, task=com.github.games647.changeskin.bungee.tasks.SkinUpdater@64daa6fb, delay=0, period=0, running=true) encountered an exception
java.lang.NoSuchMethodError: net.md_5.bungee.connection.LoginResult.<init>(Ljava/lang/String;[Lnet/md_5/bungee/connection/LoginResult$Property;)V
	at com.github.games647.changeskin.bungee.ChangeSkinBungee.applySkin(ChangeSkinBungee.java:168)
	at com.github.games647.changeskin.bungee.tasks.SkinUpdater.run(SkinUpdater.java:71)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
03:33:11 [INFO] Using OpenSSL based native cipher.
03:33:11 [INFO] Using native code compressor
``

**List of plugins in /BungeeCord/plugins**

YAMLER-Bungee-2.4.0-SHANPSHOP
VPNGuardBungee
Movemenow-1.2-17.jar
LuckPerms-Bungee-3.2.25
FastLogin
CommandControl
BungeeChat-2.0.3.2_643
BungeeAuthMeBridge
BungeeAdminTools-1.4.3-basics

**Let me know if a list of plugins is needed on my Spigot server as well, but the error only appears in my BungeeCord console.**

**Comment by games647** [comment]
Duplicate #72
