### ISSUE TITLE
No skins for cracked players with premium username

### ISSUE THREAD

**Issue by kaal-1** [games647/ChangeSkin#79]
Bungeecord
Spigot 1.8.8 (Lobby)
SpongeForge 1.10.2

Authme + FastLogin

I have ChangeSkin on all of them with the same config (same mysql database), but only players who have Premium accounts have skins.

I don't know if it's relevant, but in the lobby console I get this everytime a player logs in: https://hastebin.com/zowisuwosu.vbs

**Comment by kaal-1** [comment]
Ok the skins are working in the lobby, just not on the sponge server...

https://hastebin.com/eyuwirajiy.scala

**Comment by games647** [comment]
SpongeForge doesn't include the driver of MySQL. It includes the one of MariaDB a fork of MySQL. You should able to switch without any issues just change the driver to:

>org.mariadb.jdbc.Driver

**Comment by kaal-1** [comment]
Should I switch the spigot server and bungee to mariadb too?

**Comment by games647** [comment]
No only sponge.

**Comment by kaal-1** [comment]
It works... It would be nice if this was in the default config file.. It doesn't make any sense to come with a default driver that does not work...

Thank you :)
