### ISSUE TITLE
API 7 support?

### ISSUE THREAD

**Issue by kaal-1** [games647/ChangeSkin#82]
Does the plugin support API 7 (Sponge)? I tried using it on a 1.12 spongeforge server but the skins are not being restored.
Thank you in advance.

**Comment by games647** [comment]
Any errors?

**Comment by kaal-1** [comment]
Yeah the skins are not restored and the commands are not working.
Error occurred while executing command: null

**Comment by games647** [comment]
Which plugin version do you tried?

**Comment by gartnerleandro** [comment]
I have this error when execute /ChangeSkin + [skin] maybe it helps... I'm using an spongeforge server v1.11.2

`29.10 09:20:58 [Server] Server thread/INFO [nucleus]: Lokoso20 ran the command: /ChangeSkin http://www.minecraftskins.com/thumbnails/green-playbutton-boy-11644344.png
29.10 09:20:58 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'ChangeSkin http://www.minecraftskins.com/thumbnails/green-playbutton-boy-11644344.png' for source EntityPlayerMP['Lokoso20'/371, l='world', x=128.50, y=64.00, z=255.50]: null
29.10 09:20:58 [Server] INFO java.lang.NullPointerException
29.10 09:20:58 [Server] INFO at com.github.games647.changeskin.sponge.commands.SetSkinCommand.execute(SetSkinCommand.java:32) ~[SetSkinCommand.class:?]
29.10 09:20:58 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.11.2-2476-6.1.0-BETA-2699]
29.10 09:20:58 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.11.2-2476-6.1.0-BETA-2699]
29.10 09:20:58 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:296) ~[SpongeCommandManager.class:1.11.2-2476-6.1.0-BETA-2699]
29.10 09:20:58 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
29.10 09:20:58 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:904) ~[mi.class:?]
29.10 09:20:58 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:883) ~[mi.class:?]
29.10 09:20:58 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[ip.class:?]
29.10 09:20:58 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[ip.class:?]
29.10 09:20:58 [Server] INFO at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:145) ~[PacketUtil.class:1.11.2-2476-6.1.0-BETA-2699]
29.10 09:20:58 [Server] INFO at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.11.2-2476-6.1.0-BETA-2699]
29.10 09:20:58 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:144) [PacketUtil.class:1.11.2-2476-6.1.0-BETA-2699]
29.10 09:20:58 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjm000(SourceFile:539) [fo$1.class:?]
29.10 09:20:58 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
29.10 09:20:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
29.10 09:20:58 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
29.10 09:20:58 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
29.10 09:20:58 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:257) [SpongeImplHooks.class:1.11.2-2476-6.1.0-BETA-2699]
29.10 09:20:58 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zhl000(MinecraftServer.java:3969) [MinecraftServer.class:?]
29.10 09:20:58 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
29.10 09:20:58 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
29.10 09:20:58 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
29.10 09:20:58 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
29.10 09:20:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

**Comment by games647** [comment]
@gartnerleandro Please create a new ticket with all related details.
