### ISSUE TITLE
Bungeecord / MySQL

### ISSUE THREAD

**Issue by AodX** [games647/ChangeSkin#85]
Hello,
i had SkinChange on my server for along time, but i was on Spigot, now i moved to a VPS, and i have a Bungeecord server, so i got some problems, like... the plugin commands doesn't work at all..

i want to make sure if i'm doing my Config right
my config file is same for all servers even Bungeecord 
and thats my config file
[config.zip](https://github.com/games647/ChangeSkin/files/1290813/config.zip)
----

**Comment by games647** [comment]
Please post your server log

**Comment by AodX** [comment]
i told you more than 3 times... i don't get anything in the console

and im not ready to keep restarting my whole server and lose players :(

**Comment by games647** [comment]
Please just post your bungee log. The proxy.log file. I want to see the debug code.

**Comment by AodX** [comment]
ill add it tonight, and ill turn on the server, and ill let you know what happen to it okay ?

**Comment by AodX** [comment]
okay done
i got the ChangeSkin Plugin on my Bungeecord and Lobby 
and setup everything well
and got the same problem

those are the logs
( Bungeecord Logs => https://hastebin.com/jaxomibedo.xml  )
( Lobby Logs =>https://hastebin.com/wiqorebubo.md  )

**Comment by AodX** [comment]
The Error maybe on Line 87 in Bungeecord's Logs

**Comment by games647** [comment]
>java.lang.RuntimeException: Failed to load class of driverClassName [org.sqlite.JDBC] in either of HikariConfig class loader or Thread context classloader

Just like I assumed. There is an error. As the BungeeCord setup guide says BungeeCord doesn't include the driver for SQLite, so you have to configure it to use MySQL or MariaDB.

**Comment by AodX** [comment]
Dude ... look i did it
https://hastebin.com/iyoxotulak.php

**i changed my real MySQL password to (MyPassword) Just because i don't like to share passwords**

but in the Config file, its the Right one

**Comment by AodX** [comment]
so whats wrong about it ?

**Comment by games647** [comment]
>Dude ... look i did it

I edited the comment. I guess it's either the indentation or the blank line. Please try to make the it directly under the parent key storage:

```yaml
storage:
    driver: com.mysql.jdbc.Driver
    host: localhost
    port: 3306
    database: database
    username: user
    password: pass
```

**Comment by AodX** [comment]
okay ill give it a try

**Comment by AodX** [comment]
Thanks <3
its working 

But i have a question, do i have to add the Plugin to all servers or just bungeecord ?
because its working from Bungeecord only

what is the difference ??

**Comment by games647** [comment]
You have to add it to all servers and BungeeCord if you want use the instant skin change feature.
