### ISSUE TITLE
BungeeCord doesn't save skin selection

### ISSUE THREAD

**Issue by andramil** [games647/ChangeSkin#86]
Instructions says that "Activate BungeeCord support in your spigot configuration" but there is none BC support in my config. 

```
# ChangeSkin config

# Here you can specify default skins for player who do not have a skin
# The entries from this list will be selected in random order
#
# Lists are created like this:
#default-skins:
#    - 0aaa2c13-922a-411b-b655-9b8c08404695
#    - 069a79f4-44e9-4726-a5be-fca90e38aaf5
#
# If this list is empty no skin will be selected
default-skins: []

# If the player does not have a skin and hasn't chosen one with /setskin
# this will try to re-download using the username of the player
restoreSkins: false

# Should the skins apply instantly without re-login
# The player will be invisible for a shorten time
instantSkinChange: true

# Should the plugin check for skin specific permissions nodes like
# changeskin.skin.whitelist.uuid
# changeskin.skin.whitelist.* allows all skins
#
# The plugin checks only if the player has one of these and will not check all of them
# Examples:
#   Whitelist:
#       Give the players the permission changeskin.skin.whitelist.uuid
#       or changeskin.skin.whitelist.* for all skins
#
#   Blacklist:
#       Give your players this permission changeskin.skin.whitelist.*
#       and a negative (- before the permission) permission: '-changeskin.skin.whitelist.uuid'
#       |-> This means all skins are allowed except the ones with the uuid in the blacklist list
skinPermission: false

# A number in seconds which the player have to wait before changing the skin again
cooldown: 0

# How many requests should be established until the plugin uses the third-party API https://mcapi.ca/
# Once this number is reached in a range of ten minutes it will start connecting to https://mcapi.ca/ for the next ten
# minutes.
# This option exists in order to workaround the rate-limiting. Name -> UUID are fetched in the same way like heads
mojang-request-limit: 600

# Only relevant for BungeeCord
# Here you can ignore certain servers in order to make use of lazy loading -> load the player data only
# if they are on the allowed servers
#
# This can be used against bot attacks
# If this is empty, nothing will be ignored
server-blacklist: []
# Lists are created like this:
#server-blacklist:
#    - pvp
#    - lobby

# Actually I don't want that you put your credentials here, but it seems there is no easier way to do it.
# See my statement here: https://www.spigotmc.org/threads/changeskin.138380/page-15#post-1736265
#
# You can follow this guide on how to upload and use a skin:
# https://www.spigotmc.org/threads/changeskin.138380/page-19#post-1792019
#
# Example:
# upload-accounts:
#     - EMAIL:PASSWORD
#     - EMAIL:PASSWORD
upload-accounts: []

# If you have a BungeeCord server, this option might be relevant for you.
# If you activate this option, the permission will be checked on the bukkit server and only on the bukkit server.
#
# This requires to install the plugin on the bukkit server too in order to send the response to the bungeecord server**
#
# You still have to give the users the permission on the BungeeCord server in order to execute the command, but the bukkit
# server will verify if the user has the permissions on the backend server too.
bukkit-permissions: true

# This automatically re-fetches the skin from Mojang if the skin is older than x minutes
# This value should be at least one minute, because that's the rate-limit by Mojang
# -1 disables it
auto-skin-update: -1

# Database configuration
# Warning: If you use BungeeCord, you should switch to MySQL, because BungeeCord has only a driver for MySQL
storage:
# Single file SQLite database
#    driver: org.sqlite.JDBC
    # File location
#    database: '{pluginDir}/ChangeSkin.db'

# MySQL / MariaDB
# If you using Sponge please change the driver name to org.mariadb.jdbc.Driver
    driver: com.mysql.jdbc.Driver
    host: bb
    port: 3306
    database: bb
    username: bb
    password: bb
    # It's strongly recommended to enable SSL and setup a SSL certificate if the MySQL server isn't running on the same
    # machine
    # useSSL: false


# HTTP proxies for connecting to the Mojang servers in order to resolve the player name to UUID.
# This is a workaround to prevent rate-limiting by Mojang. These proxies will only be used once your server hit
# the rate-limit or the custom value above.
# Please make sure you use reliable proxies.
proxies:
  # 'IP:Port' or 'Domain:Port'
  # - 'xyz.com:1337'
  # - 'test.com:5131'

```

**Comment by games647** [comment]
It's inside your spigot.yml

**Comment by andramil** [comment]
Ok, after changing to true, no commands is working. There is NO information about "this command dont exist" and there is NO errors or other informations than:
`[12:30:01 INFO]: Cry_Sis issued server command: /setskin miczel100
`
Nothink is happening.

**Comment by games647** [comment]
Do you installed the plugin on BungeeCord?

**Comment by andramil** [comment]
Yes oc

**Comment by andramil** [comment]
Ok i repaired it. It worked but even i gave myslef permission in bungee config it says i dont have permission ;/

**Comment by games647** [comment]
It uses the Bungeecord permission system. So you have to activate the permissions in the config.yml of your BungeeCord server (not ChangeSkin).

**Comment by andramil** [comment]
changeskin.command.setskin.* - All the commands below
didnt work - i had to put this two to work:
changeskin.command.setskin - Set your own skin
changeskin.command.setskin.other - Set the skin of other players

**Comment by games647** [comment]
BungeeCord doesn't support wildcard permissions.

**Comment by andramil** [comment]
Ok, I have last problem:
I have settings:
`restoreSkins: true`

I have MC Premium with my own skin (one-eyed pirate). When I use /setskin miczel100 I get skin of my friend (medic) but when I rejoin I have pirate skin again. 

Even if I use MC NonPremium after relog im back to Alex.

**Comment by andramil** [comment]
With
`restoreSkins: false`
It works but I have nonpremium server so it dont restore Premium users skin

**Comment by games647** [comment]
So it looks like it doesn't save the skin changes if you manually choose a skin. Is that correct?

**Comment by andramil** [comment]
Yep

**Comment by games647** [comment]
Do you use the server blacklist feature?

**Comment by andramil** [comment]
Nope.
Skin blacklist:
`# Should the plugin check for skin specific permissions nodes like
# changeskin.skin.whitelist.uuid
# changeskin.skin.whitelist.* allows all skins
#
# The plugin checks only if the player has one of these and will not check all of them
# Examples:
#   Whitelist:
#       Give the players the permission changeskin.skin.whitelist.uuid
#       or changeskin.skin.whitelist.* for all skins
#
#   Blacklist:
#       Give your players this permission changeskin.skin.whitelist.*
#       and a negative (- before the permission) permission: '-changeskin.skin.whitelist.uuid'
#       |-> This means all skins are allowed except the ones with the uuid in the blacklist list
skinPermission: false`

server blacklist:
`# Only relevant for BungeeCord
# Here you can ignore certain servers in order to make use of lazy loading -> load the player data only
# if they are on the allowed servers
#
# This can be used against bot attacks
# If this is empty, nothing will be ignored
server-blacklist: []
# Lists are created like this:
#server-blacklist:
#    - pvp
#    - lobby`

**Comment by games647** [comment]
Could you try a dev-build please.

**Comment by andramil** [comment]
After short testing it seems to working corectly.
Also, in dev-build random skin for people without skin (premium or setskin) is working. On normal build this didnt work for me.

**Comment by andramil** [comment]
After setting default skins, savingskin changed by /setskin stop working. It didnt work even on RestoreSkins: false.
Everytime i loggout or connect to difrent server it reset to my original skin or to Steve skin (on RestoreSkin: false)
