### ISSUE TITLE
Skins reset on each player login (( Bungeecord ))

### ISSUE THREAD

**Issue by AodX** [games647/ChangeSkin#88]
Hello,

im using Bungeecord with the latest build of ChangeSkin on all my servers 

its working well, but 

when players (Cracked ones ) Join they don't get the skin they had

Whats wrong ?

**Comment by games647** [comment]
@AodX See #68

**Comment by AodX** [comment]
@games647 i saw #68 and #86 
but you didn't fix the problem there, or i didn't get it :(

**Comment by games647** [comment]
Just download a dev-build.

**Comment by AodX** [comment]
Thanks 👍

**Comment by games647** [comment]
That's what the last comment on that ticket was.........
