### ISSUE TITLE
Instant skin change doesn't change skin

### ISSUE THREAD

**Issue by TrueDimaGaming** [games647/ChangeSkin#91]
### What behaviour is observed:
When I do /setskin <skin>, It reloads the World But does not Change the Skin.

### Plugin list:
http://prntscr.com/grqn5y

### Environment description
BungeeCord Network

### Plugin version:
Latest

### Error Log:
There is none.

**Comment by games647** [comment]
Does it work after you rejoin the server?

**Comment by TrueDimaGaming** [comment]
No.

**Comment by games647** [comment]
Please post your startup log of the BungeeCord server.

**Comment by TrueDimaGaming** [comment]
Proxy?

**Comment by games647** [comment]
proxy.log.* are the files.

**Comment by TrueDimaGaming** [comment]
[proxy.log](https://github.com/games647/ChangeSkin/files/1347134/proxy.log)

**Comment by games647** [comment]
I need the startup log where Bungee starts

**Comment by TrueDimaGaming** [comment]
01.10 14:59:19 [Multicraft] Loading server properties
01.10 14:59:19 [Multicraft] Starting server!
01.10 14:59:19 [Multicraft] Loaded config for "BungeeCord (must provide your own BungeeCord.jar)"
01.10 14:59:20 [Multicraft] Updating eula.txt file
01.10 14:59:20 [Server] INFO *** Warning, this build is outdated ***
01.10 14:59:20 [Server] INFO *** Please download a new build from http://ci.md-5.net/job/BungeeCord ***
01.10 14:59:20 [Server] INFO *** You will get NO support regarding this build ***
01.10 14:59:20 [Server] INFO *** Server will start in 10 seconds ***
01.10 14:59:31 [Server] INFO Using OpenSSL based native cipher.
01.10 14:59:31 [Server] INFO Using native code compressor
01.10 14:59:31 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:eab710b:1239
01.10 14:59:31 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
01.10 14:59:31 [Server] INFO Epoll is working, utilising it!
01.10 14:59:31 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
01.10 14:59:31 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
01.10 14:59:31 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
01.10 14:59:31 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
01.10 14:59:31 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
01.10 14:59:31 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
01.10 14:59:31 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:31 [Server] INFO Loaded plugin ChangeSkin version 2.4.2 by games647, https://github.com/games647/ChangeSkin/graphs/contributors
01.10 14:59:31 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:31 [Server] INFO Loaded plugin BungeeStaffChat version 2.0-SNAPSHOT by Wout Ceulemans
01.10 14:59:31 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:31 [Server] INFO Loaded plugin BuycraftX version 10.2.2 by Buycraft
01.10 14:59:31 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:31 [Server] INFO Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:31 [Server] INFO Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:31 [Server] INFO Loaded plugin JustOneMoreBungee version 1.0 by Cewlt
01.10 14:59:32 [Server] WARNING Forced host server pvp is not defined
01.10 14:59:32 [Server] INFO Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:32 [Server] SEVERE Oct 01, 2017 2:59:32 PM com.zaxxer.hikari.HikariConfig setDriverClassName
01.10 14:59:32 [Server] INFO SEVERE: Failed to load class of driverClassName org.sqlite.JDBC in either of HikariConfig class classloader net.md_5.bungee.api.plugin.PluginClassloader@3c419631 or Thread context classloader sun.misc.Launcher$AppClassLoader@42a57993
01.10 14:59:32 [Server] WARNING Exception encountered when loading plugin: ChangeSkin
01.10 14:59:32 [Server] INFO java.lang.RuntimeException: Failed to load class of driverClassName [org.sqlite.JDBC] in either of HikariConfig class loader or Thread context classloader
01.10 14:59:32 [Server] INFO at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:332)
01.10 14:59:32 [Server] INFO at com.github.games647.changeskin.core.SkinStorage.<init>(SkinStorage.java:37)
01.10 14:59:32 [Server] INFO at com.github.games647.changeskin.bungee.ChangeSkinBungee.onEnable(ChangeSkinBungee.java:96)
01.10 14:59:32 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
01.10 14:59:32 [Server] INFO at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
01.10 14:59:32 [Server] INFO at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
01.10 14:59:32 [Server] INFO at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
01.10 14:59:32 [Server] INFO Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:32 [Server] INFO Enabled plugin BungeeStaffChat version 2.0-SNAPSHOT by Wout Ceulemans
01.10 14:59:32 [Server] INFO Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:32 [Server] INFO Validating your server key...
01.10 14:59:33 [Server] INFO A new version of BuycraftX (10.3) is available. Go to your server panel at https://server.buycraft.net/plugins to download the update.
01.10 14:59:33 [Server] INFO Updating coupon list...
01.10 14:59:33 [Server] INFO Enabled plugin BuycraftX version 10.2.2 by Buycraft
01.10 14:59:33 [Server] INFO Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:33 [Server] INFO Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:33 [Server] INFO Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:eab710b:1239 by SpigotMC
01.10 14:59:33 [Server] INFO Enabled plugin JustOneMoreBungee version 1.0 by Cewlt
01.10 14:59:33 [Server] Startup Listening on /149.56.147.175:25633
01.10 14:59:34 [Server] INFO Fetching all due players...
01.10 14:59:34 [Server] INFO Fetched due players (0 found).

Send

**Comment by games647** [comment]
There it is: 

>01.10 14:59:32 [Server] INFO java.lang.RuntimeException: Failed to load class of driverClassName [org.sqlite.JDBC] in either of HikariConfig class loader or Thread context classloader

As the setup guide for BungeeCord says, Bungee doesn't support SQLite databases, so you have to configure MySQL in your config.

**Comment by TrueDimaGaming** [comment]
Like this? # Database configuration
# Warning: If you use BungeeCord, you should switch to MySQL, because BungeeCord has only a driver for MySQL
storage:
# Single file SQLite database
    #driver: org.sqlite.JDBC
    # File location
    #database: '{pluginDir}/ChangeSkin.db'

# MySQL / MariaDB
# If you using Sponge please change the driver name to org.mariadb.jdbc.Driver
     driver: com.mysql.jdbc.Driver
     host: localhost
     port: 3306
     database: ChangeSkin
     username: myUser
     password: myPassword
     #It's strongly recommended to enable SSL and setup a SSL certificate if the MySQL server isn't running on the same
     #machine
     useSSL: false

**Comment by games647** [comment]
Yes, but you should edit the username, password combination that it can connect to a local running MySQL server. If you have a vServer or root-server this means that you have to install MySQL and edit the config to let it connect to it. Other game server hoster often already provide a MySQL for you only need to edit the connection properties.
