### ISSUE TITLE
Skin update

### ISSUE THREAD

**Issue by andramil** [games647/ChangeSkin#92]
Hi,
Im using build from 2017-09-12 10:43:36 # 24 

I have 
auto-skin-update: -1 
so skins of premium users don't update.
command /skinupdate dont work without
  - changeskin.command.setskin
  - changeskin.skin.whitelist.*

which is not ok.

when I set:
auto-skin-update: 1 
If I have premium account, set skin by /setskin RandomUser I have this skin of RandomUser until I relog. After relog I have my old skin. 

Can you repair at least one of this? command /skinupdate require only permission   
- changeskin.command.skinupdate

or auto-skin-update ignore people who has skin by "/setskin"

**Comment by games647** [comment]
>Can you repair at least one of this? command /skinupdate require only permission

I guess you have forward permission activated?

>or auto-skin-update ignore people who has skin by "/setskin"

Do you tried /setskin name keep? That should prevent it. I tested wrote some changes and it should be fixed in the newest dev-build, but there are some major changes too and it might not work as expected currently.
