### ISSUE TITLE
Update skin into db

### ISSUE THREAD

**Issue by Feerko** [games647/ChangeSkin#99]
Hello, i want to update skin from mineskin using mineskin api in php.

http://api.mineskin.org/get/id/12356

I have a problem with update a signature. How can i convert string to blob and update it to database?

**Comment by games647** [comment]
Base64 decode the texture data string

**Comment by Feerko** [comment]
$signature = base64_encode('lW/V3pJhlVhEap6FoAvSjeOwBc22AIaq74VeO9KXaxxL6BQ4xCfB4pm9+1vXByi1yaYq2XFN6hj8EJrK1ijk+NMBXqKJ6l2Jo35TV5uD0XUuMHcPyxe52myfLnV1ZlH1QZoXmTeWFh6lL6aRe9o13q3zwO7CybZl4ClaXSbphHho0ZsOolu4/ieiazNibM9XrOuLm89PlW7YLYxkKBlpXeTfG+nDNyQF8XhZGIfc46u0gMn6iH4q+bEKm/+kxGvppHcUa9bGGaPyfE+1s5ocbWqqs+DEgrmUSDQe5Jy3WJ4LaTWnoyVfzTxctiwkFY5FEnFaJhY7DFGWrE7SxGftwVo8uaPti6pshvT74jihn2MWhJuC6jogaWlA7mjSnjc2lnwv8tCZRpAVD+KZQmLuHPDzl2l26IskKo/bKVZrkf5HashoAxX8RpWICPIsG9egfne6KQ+s3YQB3SXzD4oOW5oWQAunBJx80cPB9zQLIoguVInW2E2WiBJd2g+Rh+lC/0+0OkzQY4cmf/3sBLsKoIjmwzvqlWW2gUt3WqYywwRrnnP/AfdpG4cbFe1cgMiSK0CV/ZQ2PSotNRguM5Od1k2HUnPWOm14uETM3aXE2lLl+vv6U17q/Z8Gp/A+Scll2gZfwc4vquILic/+U77wt6VAh02LMI+8eW4vLzHKhCA=');

i'm do it in this way for tests and i get 600-900B and skin doesn't work

**Comment by Feerko** [comment]
$signature = base64_decode('lW/V3pJhlVhEap6FoAvSjeOwBc22AIaq74VeO9KXaxxL6BQ4xCfB4pm9+1vXByi1yaYq2XFN6hj8EJrK1ijk+NMBXqKJ6l2Jo35TV5uD0XUuMHcPyxe52myfLnV1ZlH1QZoXmTeWFh6lL6aRe9o13q3zwO7CybZl4ClaXSbphHho0ZsOolu4/ieiazNibM9XrOuLm89PlW7YLYxkKBlpXeTfG+nDNyQF8XhZGIfc46u0gMn6iH4q+bEKm/+kxGvppHcUa9bGGaPyfE+1s5ocbWqqs+DEgrmUSDQe5Jy3WJ4LaTWnoyVfzTxctiwkFY5FEnFaJhY7DFGWrE7SxGftwVo8uaPti6pshvT74jihn2MWhJuC6jogaWlA7mjSnjc2lnwv8tCZRpAVD+KZQmLuHPDzl2l26IskKo/bKVZrkf5HashoAxX8RpWICPIsG9egfne6KQ+s3YQB3SXzD4oOW5oWQAunBJx80cPB9zQLIoguVInW2E2WiBJd2g+Rh+lC/0+0OkzQY4cmf/3sBLsKoIjmwzvqlWW2gUt3WqYywwRrnnP/AfdpG4cbFe1cgMiSK0CV/ZQ2PSotNRguM5Od1k2HUnPWOm14uETM3aXE2lLl+vv6U17q/Z8Gp/A+Scll2gZfwc4vquILic/+U77wt6VAh02LMI+8eW4vLzHKhCA=');

i have something like this for tests only but how to update it to mysql?

  $sql = "INSERT INTO `skinData` (`SkinID`, `DisplayName`, `Timestamp`, `UUID`, `Name`, `SlimModel`, `SkinURL`, `CapeURL`, `Signature`) VALUES (NULL, NULL, $timestamp, '$uuid', '$name', $slimmodel, '$skinurl', '$capeurl', '$signature');";

it's doesn't work

**Comment by games647** [comment]
The skin id should be incremented automatically, so you need to remove SkinId and DisplayName

**Comment by Feerko** [comment]
Ok but still doesn't work $signature part.

**Comment by games647** [comment]
You have to escape the parameter like with prepared statements.

**Comment by Feerko** [comment]
Ok i did it with statements.
I'm do it with http://api.mineskin.org/get/id/70507

`  $stmt = $conn->prepare("INSERT INTO skinData (SkinID, DisplayName, Timestamp, UUID, Name, SlimModel, SkinURL, CapeURL, Signature) VALUES (NULL, NULL, ?, ?, ?, ?, ?, ?, ?);");
  $stmt->bind_param("sssssss", $Timestamp, $UUID, $Name, $SlimModel, $skinURL, $CapeURL, $Signature);

  $Timestamp = 1511278348;
  $UUID = "fe2673ac98214d08bb692eb91af8c103";
  $Name = "mineskintest";
  $SlimModel = 0;
  $skinURL = "c143d47d52fb675b9b98333f03f8c2424082b019f9a4c1f493ff5c9d21ed";
  $CapeURL = "";
  $Signature =  base64_decode('tCYFZ7munFlrlr6gbaP7i3/yfe56Z4AQQ8oLuHHY8GUszc6iIl8twW4axcX1Vbu/XkCPy7DZj2fY6SWeuUBd/+OnjiQWCmZT3AlC1joDv/TTPx+o/049wBMRQ2Vv+8ZRhuPFePD4Fm5LFbjizl4h0ZdKZ1guM9KTs7AV6p2QybjojR0YtzoyS1qckPxw0FzU/TcI0+twvShaliJDKJdVy3C2ZUm19ON6OKCzYqWVLNsM9rzGk4BKTQf7Mmz7uvGTXom1nCgA7E53gunBBCZHLHmBzViM+KsF9Zi0bEG954DdPXlpQ2dC3+fuimerWRnzsFLZ3AwO2ZD9hmPHj/A9qydSNBPArUjwXPE/FmLgYnj5QWM3qWmrsHlEjWy12mf37zi3oetVo7jeSdFWE2tQZRjo5h0U0qBczndDL6UW+fhTj8W9qIONiO/NTcQbQadJMGcauKzwj3IVo+/gMDla6bvUbykEHpN7T5efsXd51OmgX75cTQjKwNmAg0endZZm/MrvgX7y1lDRDdSML+yA4y7D9z2BrAO0CoSJDO63qjWGfN3BSxwkPYBbQjRgviHUrcnXYOR4A7PhIxYuNZWZWHp8UgLUvTOP2BjD+rDCCnJKaxCaZuf9g3vW24yZyrXhfZHns+x9mk+y6cuE+tqKFhi5Ruaxzb0vHNuAWtfszBw=');
  $stmt->execute();`

it was add into database but /skinselect <id> doesn't work for this skin. What i do wrong?

**Comment by games647** [comment]
Signature is no string. It's binary

**Comment by Feerko** [comment]
I decode string.

**Comment by games647** [comment]
So it worked? If so please close it.

BTW you can remove more arguments like SlimMode and CapeURL, because it would use default values specified here:https://github.com/games647/ChangeSkin/blob/0cea42ede749533325b128b171780a6b0ec314c6/core/src/main/resources/create.sql#L1-L11

**Comment by Feerko** [comment]
Add skin to database works but if I try to /skinselect [id] it's doesn't work

**Comment by games647** [comment]
Do you tried /skinselect Skin-rowNumber ?

**Comment by Feerko** [comment]
Yes and i'm alex.

**Comment by games647** [comment]
>and i'm alex.

?
>Yes

What error do you got?

**Comment by Feerko** [comment]
Yes i'm trying with /skinselect Skin-[id] and i don't get my skin. I get Alex's skin https://camo.githubusercontent.com/de01eae929520976392b9780aff3dc5e991885e9/687474703a2f2f692e696d6775722e636f6d2f766262674b6e532e706e67

**Comment by games647** [comment]
Please try it with an NULL as capeurl. The alex skin shows up if the skin signature doesn't match.

**Comment by Feerko** [comment]
Doesn't work too

**Comment by games647** [comment]
Which version do you run?

**Comment by Feerko** [comment]
#38 from https://ci.xephi.fr/job/ChangeSkin/changes

**Comment by Feerko** [comment]
Why ChangeSkin have this structure of db? SkinsRestorer has only Value, Signature and Timestamp its a lot easier. Is there a chance that you will add api mineskin to your plugin in the near future?

**Comment by games647** [comment]
ChangeSkin just uses the base64 decoded value. This way you can easier which skin you actually have by having direct access to the true representation. 

Please try to invoke `packet add PLAY server PLAYER_INFO true` before changeskin sets the skin. I think there is something wrong with encoding the values.

**Comment by Feerko** [comment]
How can I invoke this packet? I just create simple php code to adding skin.

**Comment by Feerko** [comment]
^ missclick

**Comment by games647** [comment]
Sorry it's a command from ProtocolLib.

**Comment by Feerko** [comment]
Ok, i see this is command. It's still doesn't work.

**Comment by games647** [comment]
I need the output to debug.

**Comment by Feerko** [comment]
```
[19:18:10 INFO]: [ProtocolLib] Sent PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=46] to Feerko:
{ a = { name = "UPDATE_LATENCY", ordinal = 2 }, b = ({ b = 67, c = "ADVENTURE", d = com.mojang.authlib.GameProfile@56d68951[id=704cce29-d05f-3359-9464-9aa0d06a98eb,name=Feerko,properties={},legacy=false], e = NULL, a = NULL }, { b = 61, c = "ADVENTURE", d = com.mojang.authlib.GameProfile@5ccb2a8[id=5a6cab47-8354-3ed7-aa5d-adfbb0a98226,name=Delyszys,properties={textures=[com.mojang.authlib.properties.Property@361ed26]},legacy=false], e = NULL, a = NULL }) }
```

**Comment by games647** [comment]
Okay I thought it makes a deep toString. Here is a debug build. It prints a debug message on skin apply:
https://github.com/games647/ChangeSkin/releases/tag/testing

**Comment by Feerko** [comment]
```vbs
[19:26:51 WARN]: [ChangeSkin] Plugin ChangeSkin v3.0 generated an exception while executing task 345
java.lang.NullPointerException: null
        at com.github.games647.changeskin.core.shared.SharedSkinSelect.run(SharedSkinSelect.java:18) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1261]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1261]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1261]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

**Comment by games647** [comment]
This means it failed to steup the core. Please look for startup errors.

**Comment by Feerko** [comment]
There is no errors on startup. /setskin [nick] works but /skinselect [id] gives error in console

**Comment by games647** [comment]
Do you use BungeeCord?

**Comment by Feerko** [comment]
yes

**Comment by games647** [comment]
That's the issue. I found a typo. Try `/skin-select`

**Comment by Feerko** [comment]
```vbs
[19:36:42 INFO]: [ChangeSkin] Instant update for Feerko
[19:36:42 WARN]: [ChangeSkin] Task #1234 for ChangeSkin v3.0 generated an exception
java.lang.NullPointerException: null
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendPacketsSelf(SkinUpdater.java:205) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdateSelf(SkinUpdater.java:121) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdate(SkinUpdater.java:102) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.onInstantUpdate(SkinUpdater.java:94) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.run(SkinUpdater.java:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1261]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1261]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1261]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1261]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1261]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
> 
```

**Comment by games647** [comment]
Do you have the same version on Bungee and Spigot?

**Comment by Feerko** [comment]
yes

**Comment by games647** [comment]
New version is uploaded.

**Comment by Feerko** [comment]
Your site is dead? 502 Bad Gateway

**Comment by games647** [comment]
I meant the github testing url

**Comment by Feerko** [comment]
There is only previous release 34 minutes ago

**Comment by games647** [comment]
Same URL different version.

**Comment by Feerko** [comment]
[20:05:20 INFO] [ChangeSkin]: Skin update for Feerko with eyJ0aW1lc3RhbXAiOjE0ODY3NjU1NjUsInByb2ZpbGVJZCI6ImU1OWYzM2VlNGNmZTNmYzE4ZDE0OWZlZmM5ZmNhYTk2IiwicHJvZmlsZU5hbWUiOiIiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzM2NmE1NDk4ODFkNGY1NjI0Mjk4ZmFjMDQ1MmQ4YTQ5OGQ5YTQzMmRmNGZlODgyOTg2NTUzNTJkNGVmYjIifX19 SkinModel{skinId=52, encodedValue=eyJ0aW1lc3RhbXAiOjE0ODY3NjU1NjUsInByb2ZpbGVJZCI6ImU1OWYzM2VlNGNmZTNmYzE4ZDE0OWZlZmM5ZmNhYTk2IiwicHJvZmlsZU5hbWUiOiIiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzM2NmE1NDk4ODFkNGY1NjI0Mjk4ZmFjMDQ1MmQ4YTQ5OGQ5YTQzMmRmNGZlODgyOTg2NTUzNTJkNGVmYjIifX19, encodedSignature=rDjUUs+VTmIN8nEpEmQ/KQOgI9SScCZoiqAtrOPF2Eb7QtLZHmOsEQrH7QCMYPwtveIj+pbnzjQIdkM0hXzLywZEWbtaN7sH8QoiAaCGEcLZ0d1cjNDnTQwYits1iBxcemt1+q6oc2Hh6q4eLUgP+OKZjrheIDRsja3gDyIzxYG2stOkoQ6cWF871QNMczu8EyP0DytRhGzOYzLNWB9jBCrPNttIYW6inH7eDv79e7nvpsZLs+Quyg+U6EOXS6n76g6hES4oPlDZ+c5EstlQBTC7yuQMb/0CJc6PEccQ+gXmSRW2sSm9bZoYcMwRPa9QdbYhs2ILRgERLs1aQ6WiyvlYoZbXWjz+C7mv2iFpHMkDM/xQrNbeD1NeVqXrdO6tjXeGhnxJkkK/NXsJ2v3q0V9RviN2IQZJrQJP/MIiyPCd3xHz5Du8ADZZ3uzJWX5IT93Vj7W71/TtkqiewQJU/pxHSbxCDHelrYAEm7iZW842tLSlHsD7qCa1ND9xdiA0Kxl5Sjryo5SPGz0dnBEaNjYSj8uzecJmrWs35730AIx+93/hZZ87HcAEk7qqlAwPsrEGFULo2xpqEEz+xjAQOndmLUel3vZpdGA1yVggrqGdOLDzxWk39y8FjtQFr1PmazflKHIjOloP2NQLPh5K6XgZarwv3+wrlJsVqOc/FhE=, timestamp=1486765565, profileId=e59f33ee-4cfe-3fc1-8d14-9fefc9fcaa96, profileName=, signatureRequired=true, textures={SKIN=com.github.games647.changeskin.core.model.skin.TextureModel@504ab1e2}}

**Comment by Feerko** [comment]
I'm used this skin http://api.mineskin.org/get/id/7090

**Comment by games647** [comment]
I found it the profileName in your database doesn't match the name inside the skin data. (Could be a bug in mineskin?)

If you decode the string you get this:
```json
{"timestamp":1486823564991,
"profileId":"b0d4b28bc1d74889af0e8661cee96aab",
"profileName":"Yeleha",
"signatureRequired":true,
"textures":
    {"SKIN":{"url":"http://textures.minecraft.net/texture/366a549881d4f5624298fac0452d8a498d9a432df4fe88298655352d4efb2"}}}
```

If I decode the data from your database it's:
```json
{"timestamp":1486765565,
"profileId":"e59f33ee4cfe3fc18d149fefc9fcaa96",
"profileName":"",
"signatureRequired":true,
"textures":
    {"SKIN":{"url":"http://textures.minecraft.net/texture/366a549881d4f5624298fac0452d8a498d9a432df4fe88298655352d4efb2"}}}
```

As you can see the timestamp, profile id, ... is different. That's why the signature verification failed.

**Comment by Feerko** [comment]
It works when I change values. How can I get this values?

**Comment by Feerko** [comment]
Great! I see the problem and I understand it now. Thanks for your help. Is there a chance that you will add api mineskin to your plugin in the near future?

**Comment by games647** [comment]
Yes, I'm going to add it in a few weeks.

**Comment by Feerko** [comment]
Ok i did it! It's works... But only for some skins and I don't know why. 

For example I try with 10 random skins.

Doesn’t works:
70560
70561
70562
70564
70566
70567

Works:
70563
70565
70568
70569
70570

I don’t know why, there is an api:
http://api.mineskin.org/get/id/70560
http://api.mineskin.org/get/id/70563

**Comment by ziceptor** [comment]
How to convert the $Signature in the BLOB? Maybe there are tools for this? While there is no API support Mineskin, I'd like to manually add skins to the database. @games647 help me.

**Comment by ziceptor** [comment]
Is it enough to just decode from base64?

**Comment by games647** [comment]
Yes it's enough to decode it from Base64. As a result you'll get a binary output.  Keep in mind that you have to escape the data properly.

**Comment by ziceptor** [comment]
> Keep in mind that you have to escape the data properly.
The difficulties of translation. Please explain!

**Comment by games647** [comment]
mysql_real_escape_string

**Comment by ziceptor** [comment]
Thx

**Comment by ziceptor** [comment]
I have difficulties with the signature. https://github.com/MineSkin/api.mineskin.org/issues/4
@Feerko You have got to add healthy skin in the database? How do you do it?
@games647 How are you doing with this?

**Comment by games647** [comment]
@ziceptor Could you post your code

**Comment by ziceptor** [comment]
Works. This is an prototipe for SQLite.

```
<?php

//print_r(SQLite3::version());
$db = new SQLite3('ChangeSkin.db');

// min http://api.mineskin.org/get/id/1
// max http://api.mineskin.org/get/id/107508

for ($x=1; $x<107509; $x++) {

  $url = 'http://api.mineskin.org/get/id/' . $x;
  echo $url;
  echo(PHP_EOL);
  sleep(10);
  $MineSkin = file_get_contents($url);
  $MineSkinDec = json_decode($MineSkin,true);
  $MineSkinDecVal = $MineSkinDec['data']['texture']['value'];
  $MineSkinDecValB64D = base64_decode($MineSkinDecVal);
  $MineSkinDecValB64DDec = json_decode($MineSkinDecValB64D, true);
  $Timestamp = $MineSkinDecValB64DDec['timestamp'];
  $UUID = $MineSkinDecValB64DDec['profileId'];
  $Name = $MineSkinDecValB64DDec['profileName'];
  $SkinURLRAW = $MineSkinDecValB64DDec['textures']['SKIN']['url'];
  $pos = strrpos($SkinURLRAW, "/");
  $SkinURL = substr($SkinURLRAW, $pos + 1);
  $jsignature = $MineSkinDec['data']['texture']['signature'];
  $Signature = base64_decode($jsignature);
  $CapeURL = "";
  $stmt = $db->prepare('INSERT INTO skinData (Name, Timestamp, UUID, SkinURL, CapeURL, Signature) values (:Name, :Timestamp, :UUID, :SkinURL, :CapeURL, :Signature)');
  $stmt->bindValue(':Name', $Name, SQLITE3_TEXT);
  $stmt->bindValue(':Timestamp', $Timestamp, SQLITE3_INTEGER);
  $stmt->bindValue(':UUID', $UUID, SQLITE3_TEXT);
  $stmt->bindValue(':SkinURL', $SkinURL, SQLITE3_TEXT);
  $stmt->bindValue(':CapeURL', $CapeURL, SQLITE3_TEXT);
  $stmt->bindValue(':Signature', $Signature, SQLITE3_BLOB);
  $result = $stmt->execute();

}

$db->close();
```

**Comment by ziceptor** [comment]
You must add a condition. Remove all skins with `Name=InventiveGames`. They do not work.

**Comment by ziceptor** [comment]
Download more working skins. Less drop is not working. It is necessary to use the id in descending order.
